#include <string>
#include <unordered_map>
#include "language.hpp"

std::unordered_map<Locale, std::unordered_map<Lang, const char *>> strings = {
    {
        Locale::Japanese, {
            {Lang::ButtonOK, "OK"},
            {Lang::ButtonCancel, "キャンセル"},
            {Lang::FileBrowser, "ファイルブラウザ"},
            {Lang::DirectoryList, "ディレクトリリスト"},
            {Lang::FileName, "ファイル名"},
            {Lang::FileSize, "サイズ"},
            {Lang::OptionsTitle, "オプション"},
            {Lang::OptionsSelectAll, "すべて選択"},
            {Lang::OptionsClearAll, "すべてクリア"},
            {Lang::OptionsProperties, "プロパティ"},
            {Lang::OptionsRename, "名前を変更"},
            {Lang::OptionsNewFolder, "新しいフォルダ"},
            {Lang::OptionsNewFile, "新しいファイル"},
            {Lang::OptionsCopy, "コピー"},
            {Lang::OptionsMove, "移動"},
            {Lang::OptionsPaste, "貼り付け"},
            {Lang::OptionsDelete, "削除"},
            {Lang::OptionsSetArchiveBit, "アーカイブビットを設定"},
            {Lang::OptionsRenamePrompt, "名前を入力"},
            {Lang::OptionsFolderPrompt, "フォルダ名を入力"},
            {Lang::OptionsFilePrompt, "ファイル名を入力"},
            {Lang::OptionsCopying, "コピー中:"},
            {Lang::PropertiesName, "名前: "},
            {Lang::PropertiesSize, "サイズ: "},
            {Lang::PropertiesCreated, "作成日: "},
            {Lang::PropertiesModified, "変更日: "},
            {Lang::PropertiesAccessed, "アクセス日: "},
            {Lang::PropertiesWidth, "幅: "},
            {Lang::PropertiesHeight, "高さ: "},
            {Lang::DeleteMessage, "この操作は元に戻せません。"},
            {Lang::DeleteMultiplePrompt, "以下のものを削除しますか:"},
            {Lang::DeletePrompt, "削除しますか "},
            {Lang::ArchiveTitle, "アーカイブを展開"},
            {Lang::ArchiveMessage, "この操作には時間がかかる場合があります。"},
            {Lang::ArchivePrompt, "展開しますか "},
            {Lang::ArchiveExtracting, "展開中:"},
            {Lang::SettingsTitle, "設定"},
            {Lang::SettingsSortTitle, "ソート設定"},
            {Lang::SettingsLanguageTitle, "言語"},
            {Lang::SettingsUSBTitle, "USB"},
            {Lang::SettingsUSBUnmount, "USBデバイスのアンマウント"},
            {Lang::SettingsImageViewTitle, "画像ビューア"},
            {Lang::SettingsDevOptsTitle, "開発者オプション"},
            {Lang::SettingsMultiLangTitle, "多言語サポート（起動速度を上げるには無効にする）"},
            {Lang::SettingsFullCharsetTitle, "フル文字セットサポート（アプレットモードでは実行できません）"},
            {Lang::SettingsAboutTitle, "情報"},
            {Lang::SettingsCheckForUpdates, "アップデートを確認"},
            {Lang::SettingsImageViewFilenameToggle, " ファイル名を表示"},
            {Lang::SettingsDevOptsLogsToggle, " ログを有効化"},
            {Lang::SettingsMultiLangLogsToggle, " 多言語サポートを有効化"},
            {Lang::SettingsFullCharsetLogsToggle, " フル文字セットサポートを有効化"},
            {Lang::SettingsAboutVersion, "バージョン"},
            {Lang::SettingsAboutAuthor, "著者"},
            {Lang::SettingsAboutBanner, "バナー"},
            {Lang::UpdateTitle, "アップデート"},
            {Lang::UpdateNetworkError, "ネットワークに接続できませんでした。"},
            {Lang::UpdateAvailable, "アップデートが利用可能です。"},
            {Lang::UpdatePrompt, "NX-Shellバージョンをダウンロードしてインストールしますか "},
            {Lang::UpdateSuccess, "アップデートに成功しました。"},
            {Lang::UpdateRestart, "アプリケーションを終了して再実行してください。"},
            {Lang::UpdateNotAvailable, "最新バージョンを使用しています。"},
            {Lang::USBUnmountPrompt, "接続されているすべてのUSBデバイスをアンマウントしますか？"},
            {Lang::USBUnmountSuccess, "USBデバイスを安全に取り外すことができるようになりました。"},
            {Lang::KeyboardEmpty, "名前を空にすることはできません。"},
            {Lang::CommonYes, "はい"},
            {Lang::CommonNo, "いいえ"},
            {Lang::CommonOn, "オン"},
            {Lang::CommonOff, "オフ"},
            {Lang::TextEditorStatusLine, "行: "},
            {Lang::TextEditorStatusCol, "列: "},
            {Lang::TextEditorStatusView, "表示: "},
            {Lang::TextEditorStatusModified, "更新: "},
            {Lang::TextEditorStatusSelect, "選択: "},
            {Lang::TextEditorStatusFileSize, "ファイルサイズ: "},
            {Lang::TextEditorStatusFileOpened, "ファイル読み込み完了: "},
            {Lang::TextEditorEditLine, "行編集: "},
            {Lang::TextEditorUpdatedLine, "行更新: "},
            {Lang::TextEditorCancelEdit, "編集をキャンセル"},
            {Lang::TextEditorStatusChangesUnsaved, "保存されていない変更があります！もう一度マイナスボタンを押すと終了します"},
            {Lang::TextEditorStatusSaved, "正常に保存されました: "},
            {Lang::TextEditorStatusSaveFailed, "エラー: ファイルの保存に失敗しました!"},
            {Lang::TextEditorStatusNoChangesToSave, "保存する変更はありません"},
            {Lang::TextEditorStatusCopiedCharacters, "コピーされた文字: "},
            {Lang::TextEditorStatusNoTextToCopy, "コピーするテキストが選択されていません"},
            {Lang::TextEditorStatusPasted, "クリップボードから貼り付け"},
            {Lang::TextEditorStatusClipboardEmpty, "クリップボードは空です"},
            {Lang::TextEditorStatusUndoSuccessful, "元に戻す成功"},
            {Lang::TextEditorStatusNothingToUndo, "元に戻す操作がありません"},
            {Lang::TextEditorStatusRedoSuccessful, "やり直し成功"},
            {Lang::TextEditorStatusNothingToRedo, "やり直す操作がありません"},
            {Lang::TextEditorStatusFindText, "テキスト検索:"},
            {Lang::TextEditorStatusTextFound, "見つかりました: \""},
            {Lang::TextEditorStatusTextNotFound, "\" 見つかりません"},
            {Lang::TextEditorStatusSelectModeOn, "選択モード オン"},
            {Lang::TextEditorStatusSelectModeOff, "選択モード オフ"},
            {Lang::TextEditorStatusDeletedSelectedText, "選択されたテキストを削除しました"},
            {Lang::TextEditorStatusDeletedPreCharacter, "バックスペース (前の文字を削除)"},
            {Lang::TextEditorStatusDeleteForwardCharacter, "次の文字を削除"},
            {Lang::TextEditorStatusInsertNewLine, "新しい行を挿入"},
            {Lang::TextEditorControls, "| \uE0EF 保存 | \uE0F0 終了 | \uE0E0 編集 | \uE0E1 削除 | \uE0E6 元に戻す | \uE0E7 やり直す | \uE0E4+\uE0ED/\uE0EE 選択 | \uE0E2 コピー | \uE0E3 貼り付け | \uE0E5 検索 |"},
            {Lang::TextEditorExitPrompt, "ファイルが大きすぎます。アプレットモード以外で実行してください！"},
        }
    },
    {
        Locale::English, {
            {Lang::ButtonOK,  "OK"},
            {Lang::ButtonCancel,  "Cancel"},
            {Lang::FileBrowser,  "File Browser"},
            {Lang::DirectoryList,  "Directory List"},
            {Lang::FileName,  "Filename"},
            {Lang::FileSize,  "Size"},
            {Lang::OptionsTitle,  "Options"},
            {Lang::OptionsSelectAll,  "Select All"},
            {Lang::OptionsClearAll,  "Clear All"},
            {Lang::OptionsProperties,  "Properties"},
            {Lang::OptionsRename,  "Rename"},
            {Lang::OptionsNewFolder,  "New Folder"},
            {Lang::OptionsNewFile,  "New File"},
            {Lang::OptionsCopy,  "Copy"},
            {Lang::OptionsMove,  "Move"},
            {Lang::OptionsPaste,  "Paste"},
            {Lang::OptionsDelete,  "Delete"},
            {Lang::OptionsSetArchiveBit,  "Set Archive Bit"},
            {Lang::OptionsRenamePrompt,  "Enter name"},
            {Lang::OptionsFolderPrompt,  "Enter folder name"},
            {Lang::OptionsFilePrompt,  "Enter file name"},
            {Lang::OptionsCopying,  "Copying:"},
            {Lang::PropertiesName,  "Name: "},
            {Lang::PropertiesSize,  "Size: "},
            {Lang::PropertiesCreated,  "Created: "},
            {Lang::PropertiesModified,  "Modified: "},
            {Lang::PropertiesAccessed,  "Accessed: "},
            {Lang::PropertiesWidth,  "Width: "},
            {Lang::PropertiesHeight,  "Height: "},
            {Lang::DeleteMessage,  "This action cannot be undone."},
            {Lang::DeleteMultiplePrompt,  "Do you wish to delete the following:"},
            {Lang::DeletePrompt,  "Do you wish to delete "},
            {Lang::ArchiveTitle,  "Extract archive"},
            {Lang::ArchiveMessage,  "This action may take a while."},
            {Lang::ArchivePrompt,  "Do you wish to extract "},
            {Lang::ArchiveExtracting,  "Extracting:"},
            {Lang::SettingsTitle,  "Settings"},
            {Lang::SettingsSortTitle,  "Sort Settings"},
            {Lang::SettingsLanguageTitle,  "Language"},
            {Lang::SettingsUSBTitle,  "USB"},
            {Lang::SettingsUSBUnmount,  "Unmount USB devices"},
            {Lang::SettingsImageViewTitle,  "Image Viewer"},
            {Lang::SettingsDevOptsTitle,  "Developer Options"},
            {Lang::SettingsMultiLangTitle,  "Multilingual support (disable to speed up startup)"},
            {Lang::SettingsFullCharsetTitle,  "Full character set support (cannot run in applet mode)"},
            {Lang::SettingsAboutTitle,  "About"},
            {Lang::SettingsCheckForUpdates,  "Check for Updates"},
            {Lang::SettingsImageViewFilenameToggle,  " Display filename"},
            {Lang::SettingsDevOptsLogsToggle,  " Enable logs"},
            {Lang::SettingsMultiLangLogsToggle,  " Enable support for multi-language"},
            {Lang::SettingsFullCharsetLogsToggle,  " Enable support for full character set"},
            {Lang::SettingsAboutVersion,  "version"},
            {Lang::SettingsAboutAuthor,  "Author"},
            {Lang::SettingsAboutBanner,  "Banner"},
            {Lang::UpdateTitle,  "Update"},
            {Lang::UpdateNetworkError,  "Could not connect to network."},
            {Lang::UpdateAvailable,  "An update is available."},
            {Lang::UpdatePrompt,  "Do you wish to download and install NX-Shell version "},
            {Lang::UpdateSuccess,  "Update was successful."},
            {Lang::UpdateRestart,  "Please exit and rerun the application."},
            {Lang::UpdateNotAvailable,  "You are on the latest version."},
            {Lang::USBUnmountPrompt,  "Do you wish to unmount all the connected USB devices?"},
            {Lang::USBUnmountSuccess,  "The USB device can now be safely removed."},
            {Lang::KeyboardEmpty,  "The name cannot be empty."},
            {Lang::CommonYes,  "Yes"},
            {Lang::CommonNo,  "No"},
            {Lang::CommonOn,  "ON"},
            {Lang::CommonOff,  "OFF"},
            {Lang::TextEditorStatusLine,  "Line: "},
            {Lang::TextEditorStatusCol,  "Col: "},
            {Lang::TextEditorStatusView,  "View: "},
            {Lang::TextEditorStatusModified,  "Modified: "},
            {Lang::TextEditorStatusSelect,  "Select: "},
            {Lang::TextEditorStatusFileSize, "File size: "},
            {Lang::TextEditorStatusFileOpened,  "File loaded: "},
            {Lang::TextEditorEditLine,  "Edit line: "},
            {Lang::TextEditorUpdatedLine,  "Updated line: "},
            {Lang::TextEditorCancelEdit,  "Cancel edit"},
            {Lang::TextEditorStatusChangesUnsaved,  "Unsaved changes! Press Minus again to exit"},
            {Lang::TextEditorStatusSaved,  "Saved successfully: "},
            {Lang::TextEditorStatusSaveFailed,  "ERROR: Failed to save file!"},
            {Lang::TextEditorStatusNoChangesToSave,  "No changes to save"},
            {Lang::TextEditorStatusCopiedCharacters,  "Copied characters: "},
            {Lang::TextEditorStatusNoTextToCopy,  "No text selected to copy"},
            {Lang::TextEditorStatusPasted,  "Pasted from clipboard"},
            {Lang::TextEditorStatusClipboardEmpty,  "Clipboard is empty"},
            {Lang::TextEditorStatusUndoSuccessful,  "Undo successful"},
            {Lang::TextEditorStatusNothingToUndo,  "Nothing to undo"},
            {Lang::TextEditorStatusRedoSuccessful,  "Redo successful"},
            {Lang::TextEditorStatusNothingToRedo,  "Nothing to redo"},
            {Lang::TextEditorStatusFindText,  "Find text:"},
            {Lang::TextEditorStatusTextFound,  "Found: \""},
            {Lang::TextEditorStatusTextNotFound,  "\" not found"},
            {Lang::TextEditorStatusSelectModeOn,  "Select mode ON"},
            {Lang::TextEditorStatusSelectModeOff,  "Select mode OFF"},
            {Lang::TextEditorStatusDeletedSelectedText,  "Deleted selected text"},
            {Lang::TextEditorStatusDeletedPreCharacter,  "Backspace (deleted previous character)"},
            {Lang::TextEditorStatusDeleteForwardCharacter,  "Deleted forward character"},
            {Lang::TextEditorStatusInsertNewLine,  "Inserted new line"},
            {Lang::TextEditorControls, "| \uE0EF Save | \uE0F0 Exit | \uE0E0 Edit | \uE0E1 Delete | \uE0E6 Undo | \uE0E7 Redo | \uE0E4+\uE0ED/\uE0EE Select | \uE0E2 Copy | \uE0E3 Paste | \uE0E5 Search |"},
            {Lang::TextEditorExitPrompt, "File is too large. Please run in non-applet mode!"},
        }
    },
    {
        Locale::French, {
            {Lang::ButtonOK, "OK"},
            {Lang::ButtonCancel, "Annuler"},
            {Lang::FileBrowser, "Navigateur de fichiers"},
            {Lang::DirectoryList, "Liste des répertoires"},
            {Lang::FileName, "Nom de fichier"},
            {Lang::FileSize, "Taille"},
            {Lang::OptionsTitle, "Options"},
            {Lang::OptionsSelectAll, "Tout sélectionner"},
            {Lang::OptionsClearAll, "Tout effacer"},
            {Lang::OptionsProperties, "Propriétés"},
            {Lang::OptionsRename, "Renommer"},
            {Lang::OptionsNewFolder, "Nouveau dossier"},
            {Lang::OptionsNewFile, "Nouveau fichier"},
            {Lang::OptionsCopy, "Copier"},
            {Lang::OptionsMove, "Déplacer"},
            {Lang::OptionsPaste, "Coller"},
            {Lang::OptionsDelete, "Supprimer"},
            {Lang::OptionsSetArchiveBit, "Définir le bit d'archive"},
            {Lang::OptionsRenamePrompt, "Entrez le nom"},
            {Lang::OptionsFolderPrompt, "Entrez le nom du dossier"},
            {Lang::OptionsFilePrompt, "Entrez le nom du fichier"},
            {Lang::OptionsCopying, "Copie en cours:"},
            {Lang::PropertiesName, "Nom: "},
            {Lang::PropertiesSize, "Taille: "},
            {Lang::PropertiesCreated, "Création: "},
            {Lang::PropertiesModified, "Modification: "},
            {Lang::PropertiesAccessed, "Accès: "},
            {Lang::PropertiesWidth, "Largeur: "},
            {Lang::PropertiesHeight, "Hauteur: "},
            {Lang::DeleteMessage, "Cette action ne peut pas être annulée."},
            {Lang::DeleteMultiplePrompt, "Souhaitez-vous supprimer ce qui suit:"},
            {Lang::DeletePrompt, "Souhaitez-vous supprimer "},
            {Lang::ArchiveTitle, "Extraire l'archive"},
            {Lang::ArchiveMessage, "Cette action peut prendre un certain temps."},
            {Lang::ArchivePrompt, "Souhaitez-vous extraire "},
            {Lang::ArchiveExtracting, "Extraction en cours:"},
            {Lang::SettingsTitle, "Paramètres"},
            {Lang::SettingsSortTitle, "Paramètres de tri"},
            {Lang::SettingsLanguageTitle, "Langue"},
            {Lang::SettingsUSBTitle, "USB"},
            {Lang::SettingsUSBUnmount, "Démonter les périphériques USB"},
            {Lang::SettingsImageViewTitle, "Visionneuse d'images"},
            {Lang::SettingsDevOptsTitle, "Options développeur"},
            {Lang::SettingsMultiLangTitle, "Prise en charge multilingue (désactiver pour accélérer le démarrage)"},
            {Lang::SettingsFullCharsetTitle, "Prise en charge complète du jeu de caractères (ne peut pas être exécuté en mode applet)"},
            {Lang::SettingsAboutTitle, "À propos"},
            {Lang::SettingsCheckForUpdates, "Vérifier les mises à jour"},
            {Lang::SettingsImageViewFilenameToggle, " Afficher le nom du fichier"},
            {Lang::SettingsDevOptsLogsToggle, " Activer les logs"},
            {Lang::SettingsMultiLangLogsToggle, " Activer la prise en charge du multi-langue"},
            {Lang::SettingsFullCharsetLogsToggle, " Activer la prise en charge du jeu de caractères complet"},
            {Lang::SettingsAboutVersion, "version"},
            {Lang::SettingsAboutAuthor, "Auteur"},
            {Lang::SettingsAboutBanner, "Bannière"},
            {Lang::UpdateTitle, "Mise à jour"},
            {Lang::UpdateNetworkError, "Impossible de se connecter au réseau."},
            {Lang::UpdateAvailable, "Une mise à jour est disponible."},
            {Lang::UpdatePrompt, "Souhaitez-vous télécharger et installer la version NX-Shell "},
            {Lang::UpdateSuccess, "La mise à jour a réussi."},
            {Lang::UpdateRestart, "Veuillez quitter et relancer l'application."},
            {Lang::UpdateNotAvailable, "Vous disposez de la dernière version."},
            {Lang::USBUnmountPrompt, "Souhaitez-vous démonter tous les périphériques USB connectés?"},
            {Lang::USBUnmountSuccess, "Le périphérique USB peut maintenant être retiré en toute sécurité."},
            {Lang::KeyboardEmpty, "Le nom ne peut pas être vide."},
            {Lang::CommonYes, "Oui"},
            {Lang::CommonNo, "Non"},
            {Lang::CommonOn, "ACTIF"},
            {Lang::CommonOff, "INACTIF"},
            {Lang::TextEditorStatusLine, "Ligne: "},
            {Lang::TextEditorStatusCol, "Colonne: "},
            {Lang::TextEditorStatusView, "Vue: "},
            {Lang::TextEditorStatusModified, "Modifié: "},
            {Lang::TextEditorStatusSelect, "Sélection: "},
            {Lang::TextEditorStatusFileSize, "Taille du fichier: "},
            {Lang::TextEditorStatusFileOpened, "Fichier chargé: "},
            {Lang::TextEditorEditLine, "Modifier la ligne: "},
            {Lang::TextEditorUpdatedLine, "Ligne mise à jour : "},
            {Lang::TextEditorCancelEdit, "Annuler l'édition"},
            {Lang::TextEditorStatusChangesUnsaved, "Modifications non enregistrées ! Appuyez à nouveau sur Moins pour quitter"},
            {Lang::TextEditorStatusSaved, "Enregistré avec succès : "},
            {Lang::TextEditorStatusSaveFailed, "ERREUR : Échec de l'enregistrement du fichier !"},
            {Lang::TextEditorStatusNoChangesToSave, "Aucune modification à enregistrer"},
            {Lang::TextEditorStatusCopiedCharacters, "Caractères copiés : "},
            {Lang::TextEditorStatusNoTextToCopy, "Aucun texte sélectionné à copier"},
            {Lang::TextEditorStatusPasted, "Collé depuis le presse-papiers"},
            {Lang::TextEditorStatusClipboardEmpty, "Le presse-papiers est vide"},
            {Lang::TextEditorStatusUndoSuccessful, "Annulation réussie"},
            {Lang::TextEditorStatusNothingToUndo, "Rien à annuler"},
            {Lang::TextEditorStatusRedoSuccessful, "Rétablissement réussi"},
            {Lang::TextEditorStatusNothingToRedo, "Rien à rétablir"},
            {Lang::TextEditorStatusFindText, "Rechercher le texte :"},
            {Lang::TextEditorStatusTextFound, "Trouvé : \""},
            {Lang::TextEditorStatusTextNotFound, "\" non trouvé"},
            {Lang::TextEditorStatusSelectModeOn, "Mode sélection ACTIVÉ"},
            {Lang::TextEditorStatusSelectModeOff, "Mode sélection DÉSACTIVÉ"},
            {Lang::TextEditorStatusDeletedSelectedText, "Texte sélectionné supprimé"},
            {Lang::TextEditorStatusDeletedPreCharacter, "Retour arrière (caractère précédent supprimé)"},
            {Lang::TextEditorStatusDeleteForwardCharacter, "Caractère suivant supprimé"},
            {Lang::TextEditorStatusInsertNewLine, "Nouvelle ligne insérée"},
            {Lang::TextEditorControls, "| \uE0EF Enregistrer | \uE0F0 Quitter | \uE0E0 Modifier | \uE0E1 Supprimer | \uE0E6 Annuler | \uE0E7 Rétablir | \uE0E4+\uE0ED/\uE0EE Sélectionner | \uE0E2 Copier | \uE0E3 Coller | \uE0E5 Rechercher |"},
            {Lang::TextEditorExitPrompt, "Le fichier est trop volumineux. Veuillez exécuter en mode non applet !"},
        }
    },
    {
        Locale::German, {
            {Lang::ButtonOK, "OK"},
            {Lang::ButtonCancel, "Abbrechen"},
            {Lang::FileBrowser, "Dateibrowser"},
            {Lang::DirectoryList, "Verzeichnisliste"},
            {Lang::FileName, "Dateiname"},
            {Lang::FileSize, "Größe"},
            {Lang::OptionsTitle, "Optionen"},
            {Lang::OptionsSelectAll, "Alle auswählen"},
            {Lang::OptionsClearAll, "Alle löschen"},
            {Lang::OptionsProperties, "Eigenschaften"},
            {Lang::OptionsRename, "Umbenennen"},
            {Lang::OptionsNewFolder, "Neuer Ordner"},
            {Lang::OptionsNewFile, "Neue Datei"},
            {Lang::OptionsCopy, "Kopieren"},
            {Lang::OptionsMove, "Verschieben"},
            {Lang::OptionsPaste, "Einfügen"},
            {Lang::OptionsDelete, "Löschen"},
            {Lang::OptionsSetArchiveBit, "Archiv-Bit setzen"},
            {Lang::OptionsRenamePrompt, "Name eingeben"},
            {Lang::OptionsFolderPrompt, "Ordnername eingeben"},
            {Lang::OptionsFilePrompt, "Dateiname eingeben"},
            {Lang::OptionsCopying, "Kopiere:"},
            {Lang::PropertiesName, "Name: "},
            {Lang::PropertiesSize, "Größe: "},
            {Lang::PropertiesCreated, "Erstellt: "},
            {Lang::PropertiesModified, "Geändert: "},
            {Lang::PropertiesAccessed, "Zugegriffen: "},
            {Lang::PropertiesWidth, "Breite: "},
            {Lang::PropertiesHeight, "Höhe: "},
            {Lang::DeleteMessage, "Diese Aktion kann nicht rückgängig gemacht werden."},
            {Lang::DeleteMultiplePrompt, "Möchten Sie Folgendes löschen:"},
            {Lang::DeletePrompt, "Möchten Sie löschen "},
            {Lang::ArchiveTitle, "Archiv entpacken"},
            {Lang::ArchiveMessage, "Dieser Vorgang kann eine Weile dauern."},
            {Lang::ArchivePrompt, "Möchten Sie entpacken "},
            {Lang::ArchiveExtracting, "Entpacken:"},
            {Lang::SettingsTitle, "Einstellungen"},
            {Lang::SettingsSortTitle, "Sortiereinstellungen"},
            {Lang::SettingsLanguageTitle, "Sprache"},
            {Lang::SettingsUSBTitle, "USB"},
            {Lang::SettingsUSBUnmount, "USB-Geräte aushängen"},
            {Lang::SettingsImageViewTitle, "Bildbetrachter"},
            {Lang::SettingsDevOptsTitle, "Entwickleroptionen"},
            {Lang::SettingsMultiLangTitle, "Mehrsprachige Unterstützung (deaktivieren zum Beschleunigen des Starts)"},
            {Lang::SettingsFullCharsetTitle, "Vollständige Zeichensatzunterstützung (kann im Applet-Modus nicht ausgeführt werden)"},
            {Lang::SettingsAboutTitle, "Über"},
            {Lang::SettingsCheckForUpdates, "Auf Updates prüfen"},
            {Lang::SettingsImageViewFilenameToggle, " Dateiname anzeigen"},
            {Lang::SettingsDevOptsLogsToggle, " Protokolle aktivieren"},
            {Lang::SettingsMultiLangLogsToggle, " Unterstützung für mehrere Sprachen aktivieren"},
            {Lang::SettingsFullCharsetLogsToggle, " Unterstützung für vollständigen Zeichensatz aktivieren"},
            {Lang::SettingsAboutVersion, "Version"},
            {Lang::SettingsAboutAuthor, "Autor"},
            {Lang::SettingsAboutBanner, "Banner"},
            {Lang::UpdateTitle, "Update"},
            {Lang::UpdateNetworkError, "Es konnte keine Verbindung zum Netzwerk hergestellt werden."},
            {Lang::UpdateAvailable, "Ein Update ist verfügbar."},
            {Lang::UpdatePrompt, "Möchten Sie die NX-Shell-Version herunterladen und installieren? "},
            {Lang::UpdateSuccess, "Update war erfolgreich."},
            {Lang::UpdateRestart, "Bitte beenden Sie die Anwendung und starten Sie sie erneut."},
            {Lang::UpdateNotAvailable, "Sie verwenden die neueste Version."},
            {Lang::USBUnmountPrompt, "Möchten Sie alle verbundenen USB-Geräte aushängen?"},
            {Lang::USBUnmountSuccess, "Das USB-Gerät kann jetzt sicher entfernt werden."},
            {Lang::KeyboardEmpty, "Der Name darf nicht leer sein."},
            {Lang::CommonYes, "Ja"},
            {Lang::CommonNo, "Nein"},
            {Lang::CommonOn, "EIN"},
            {Lang::CommonOff, "AUS"},
            {Lang::TextEditorStatusLine, "Zeile: "},
            {Lang::TextEditorStatusCol, "Spalte: "},
            {Lang::TextEditorStatusView, "Ansicht: "},
            {Lang::TextEditorStatusModified, "Geändert: "},
            {Lang::TextEditorStatusSelect, "Auswahl: "},
            {Lang::TextEditorStatusFileSize, "Dateigröße: "},
            {Lang::TextEditorStatusFileOpened, "Datei geladen: "},
            {Lang::TextEditorEditLine, "Zeile bearbeiten: "},
            {Lang::TextEditorUpdatedLine, "Zeile aktualisiert: "},
            {Lang::TextEditorCancelEdit, "Bearbeitung abbrechen"},
            {Lang::TextEditorStatusChangesUnsaved, "Ungespeicherte Änderungen! Drücken Sie erneut Minus zum Beenden"},
            {Lang::TextEditorStatusSaved, "Erfolgreich gespeichert: "},
            {Lang::TextEditorStatusSaveFailed, "FEHLER: Fehler beim Speichern der Datei!"},
            {Lang::TextEditorStatusNoChangesToSave, "Keine Änderungen zu speichern"},
            {Lang::TextEditorStatusCopiedCharacters, "Kopierte Zeichen: "},
            {Lang::TextEditorStatusNoTextToCopy, "Kein Text zum Kopieren ausgewählt"},
            {Lang::TextEditorStatusPasted, "Aus Zwischenablage eingefügt"},
            {Lang::TextEditorStatusClipboardEmpty, "Zwischenablage ist leer"},
            {Lang::TextEditorStatusUndoSuccessful, "Rückgängig erfolgreich"},
            {Lang::TextEditorStatusNothingToUndo, "Nichts rückgängig zu machen"},
            {Lang::TextEditorStatusRedoSuccessful, "Wiederherstellen erfolgreich"},
            {Lang::TextEditorStatusNothingToRedo, "Nichts zum Wiederherstellen"},
            {Lang::TextEditorStatusFindText, "Text suchen:"},
            {Lang::TextEditorStatusTextFound, "Gefunden: \""},
            {Lang::TextEditorStatusTextNotFound, "\" nicht gefunden"},
            {Lang::TextEditorStatusSelectModeOn, "Auswahlmodus EIN"},
            {Lang::TextEditorStatusSelectModeOff, "Auswahlmodus AUS"},
            {Lang::TextEditorStatusDeletedSelectedText, "Ausgewählter Text gelöscht"},
            {Lang::TextEditorStatusDeletedPreCharacter, "Rücktaste (vorheriges Zeichen gelöscht)"},
            {Lang::TextEditorStatusDeleteForwardCharacter, "Vorwärtszeichen gelöscht"},
            {Lang::TextEditorStatusInsertNewLine, "Neue Zeile eingefügt"},
            {Lang::TextEditorControls, "| \uE0EF Speichern | \uE0F0 Beenden | \uE0E0 Bearbeiten | \uE0E1 Löschen | \uE0E6 Rückgängig | \uE0E7 Wiederherstellen | \uE0E4+\uE0ED/\uE0EE Auswählen | \uE0E2 Kopieren | \uE0E3 Einfügen | \uE0E5 Suchen |"},
            {Lang::TextEditorExitPrompt, "Datei ist zu groß. Bitte im Nicht-Applet-Modus ausführen!"},
        }
    },
    {
        Locale::Italian, {
            {Lang::ButtonOK, "OK"},
            {Lang::ButtonCancel, "Annulla"},
            {Lang::FileBrowser, "Browser dei file"},
            {Lang::DirectoryList, "Elenco delle directory"},
            {Lang::FileName, "Nome del file"},
            {Lang::FileSize, "Dimensione"},
            {Lang::OptionsTitle, "Opzioni"},
            {Lang::OptionsSelectAll, "Seleziona tutto"},
            {Lang::OptionsClearAll, "Cancella tutto"},
            {Lang::OptionsProperties, "Proprietà"},
            {Lang::OptionsRename, "Rinomina"},
            {Lang::OptionsNewFolder, "Nuova cartella"},
            {Lang::OptionsNewFile, "Nuovo file"},
            {Lang::OptionsCopy, "Copia"},
            {Lang::OptionsMove, "Sposta"},
            {Lang::OptionsPaste, "Incolla"},
            {Lang::OptionsDelete, "Elimina"},
            {Lang::OptionsSetArchiveBit, "Imposta il bit di archivio"},
            {Lang::OptionsRenamePrompt, "Inserisci nome"},
            {Lang::OptionsFolderPrompt, "Inserisci il nome della cartella"},
            {Lang::OptionsFilePrompt, "Inserisci il nome del file"},
            {Lang::OptionsCopying, "Copia in corso:"},
            {Lang::PropertiesName, "Nome: "},
            {Lang::PropertiesSize, "Dimensione: "},
            {Lang::PropertiesCreated, "Creato: "},
            {Lang::PropertiesModified, "Modificato: "},
            {Lang::PropertiesAccessed, "Accesso: "},
            {Lang::PropertiesWidth, "Larghezza: "},
            {Lang::PropertiesHeight, "Altezza: "},
            {Lang::DeleteMessage, "Questa azione non può essere annullata."},
            {Lang::DeleteMultiplePrompt, "Vuoi eliminare quanto segue:"},
            {Lang::DeletePrompt, "Vuoi eliminare "},
            {Lang::ArchiveTitle, "Estrai archivio"},
            {Lang::ArchiveMessage, "Questa azione potrebbe richiedere un po' di tempo."},
            {Lang::ArchivePrompt, "Vuoi estrarre "},
            {Lang::ArchiveExtracting, "Estrazione:"},
            {Lang::SettingsTitle, "Impostazioni"},
            {Lang::SettingsSortTitle, "Impostazioni di ordinamento"},
            {Lang::SettingsLanguageTitle, "Lingua"},
            {Lang::SettingsUSBTitle, "USB"},
            {Lang::SettingsUSBUnmount, "Smonta dispositivi USB"},
            {Lang::SettingsImageViewTitle, "Visualizzatore di immagini"},
            {Lang::SettingsDevOptsTitle, "Opzioni sviluppatore"},
            {Lang::SettingsMultiLangTitle, "Supporto multilingue (disabilita per accelerare l'avvio)"},
            {Lang::SettingsFullCharsetTitle, "Supporto completo del set di caratteri (non può essere eseguito in modalità applet)"},
            {Lang::SettingsAboutTitle, "Informazioni"},
            {Lang::SettingsCheckForUpdates, "Controlla aggiornamenti"},
            {Lang::SettingsImageViewFilenameToggle, " Visualizza nome file"},
            {Lang::SettingsDevOptsLogsToggle, " Abilita log"},
            {Lang::SettingsMultiLangLogsToggle, " Abilita supporto multilingue"},
            {Lang::SettingsFullCharsetLogsToggle, " Abilita supporto set di caratteri completo"},
            {Lang::SettingsAboutVersion, "versione"},
            {Lang::SettingsAboutAuthor, "Autore"},
            {Lang::SettingsAboutBanner, "Banner"},
            {Lang::UpdateTitle, "Aggiornamento"},
            {Lang::UpdateNetworkError, "Impossibile connettersi alla rete."},
            {Lang::UpdateAvailable, "È disponibile un aggiornamento."},
            {Lang::UpdatePrompt, "Vuoi scaricare e installare la versione NX-Shell "},
            {Lang::UpdateSuccess, "Aggiornamento riuscito."},
            {Lang::UpdateRestart, "Esci e riavvia l'applicazione."},
            {Lang::UpdateNotAvailable, "Stai utilizzando la versione più recente."},
            {Lang::USBUnmountPrompt, "Vuoi smontare tutti i dispositivi USB collegati?"},
            {Lang::USBUnmountSuccess, "Il dispositivo USB può ora essere rimosso in sicurezza."},
            {Lang::KeyboardEmpty, "Il nome non può essere vuoto."},
            {Lang::CommonYes, "Sì"},
            {Lang::CommonNo, "No"},
            {Lang::CommonOn, "ON"},
            {Lang::CommonOff, "OFF"},
            {Lang::TextEditorStatusLine, "Riga: "},
            {Lang::TextEditorStatusCol, "Colonna: "},
            {Lang::TextEditorStatusView, "Vista: "},
            {Lang::TextEditorStatusModified, "Modificato: "},
            {Lang::TextEditorStatusSelect, "Seleziona: "},
            {Lang::TextEditorStatusFileSize, "Dimensione file: "},
            {Lang::TextEditorStatusFileOpened, "File caricato: "},
            {Lang::TextEditorEditLine, "Modifica riga: "},
            {Lang::TextEditorUpdatedLine, "Riga aggiornata: "},
            {Lang::TextEditorCancelEdit, "Annulla modifica"},
            {Lang::TextEditorStatusChangesUnsaved, "Modifiche non salvate! Premi di nuovo il tasto Meno per uscire"},
            {Lang::TextEditorStatusSaved, "Salvato con successo: "},
            {Lang::TextEditorStatusSaveFailed, "ERRORE: Impossibile salvare il file!"},
            {Lang::TextEditorStatusNoChangesToSave, "Nessuna modifica da salvare"},
            {Lang::TextEditorStatusCopiedCharacters, "Caratteri copiati: "},
            {Lang::TextEditorStatusNoTextToCopy, "Nessun testo selezionato da copiare"},
            {Lang::TextEditorStatusPasted, "Incollato dagli appunti"},
            {Lang::TextEditorStatusClipboardEmpty, "Gli appunti sono vuoti"},
            {Lang::TextEditorStatusUndoSuccessful, "Annullamento riuscito"},
            {Lang::TextEditorStatusNothingToUndo, "Niente da annullare"},
            {Lang::TextEditorStatusRedoSuccessful, "Ripristino riuscito"},
            {Lang::TextEditorStatusNothingToRedo, "Niente da ripristinare"},
            {Lang::TextEditorStatusFindText, "Trova testo:"},
            {Lang::TextEditorStatusTextFound, "Trovato: \""},
            {Lang::TextEditorStatusTextNotFound, "\" non trovato"},
            {Lang::TextEditorStatusSelectModeOn, "Modalità selezione ATTIVA"},
            {Lang::TextEditorStatusSelectModeOff, "Modalità selezione DISATTIVA"},
            {Lang::TextEditorStatusDeletedSelectedText, "Testo selezionato eliminato"},
            {Lang::TextEditorStatusDeletedPreCharacter, "Backspace (carattere precedente cancellato)"},
            {Lang::TextEditorStatusDeleteForwardCharacter, "Carattere successivo cancellato"},
            {Lang::TextEditorStatusInsertNewLine, "Nuova riga inserita"},
            {Lang::TextEditorControls, "| \uE0EF Salvare | \uE0F0 Uscire | \uE0E0 Modificare | \uE0E1 Eliminare | \uE0E6 Annullare | \uE0E7 Ripristinare | \uE0E4+\uE0ED/\uE0EE Selezionare | \uE0E2 Copiare | \uE0E3 Incollare | \uE0E5 Cercare |"},
            {Lang::TextEditorExitPrompt, "Il file è troppo grande. Esegui in modalità non applet!"},
        }
    },
    {
        Locale::Spanish, {
            {Lang::ButtonOK, "OK"},
            {Lang::ButtonCancel, "Cancelar"},
            {Lang::FileBrowser, "Explorador de archivos"},
            {Lang::DirectoryList, "Lista de directorios"},
            {Lang::FileName, "Nombre de archivo"},
            {Lang::FileSize, "Tamaño"},
            {Lang::OptionsTitle, "Opciones"},
            {Lang::OptionsSelectAll, "Seleccionar todo"},
            {Lang::OptionsClearAll, "Limpiar todo"},
            {Lang::OptionsProperties, "Propiedades"},
            {Lang::OptionsRename, "Renombrar"},
            {Lang::OptionsNewFolder, "Nueva carpeta"},
            {Lang::OptionsNewFile, "Nuevo archivo"},
            {Lang::OptionsCopy, "Copiar"},
            {Lang::OptionsMove, "Mover"},
            {Lang::OptionsPaste, "Pegar"},
            {Lang::OptionsDelete, "Eliminar"},
            {Lang::OptionsSetArchiveBit, "Establecer bit de archivo"},
            {Lang::OptionsRenamePrompt, "Introducir nombre"},
            {Lang::OptionsFolderPrompt, "Introducir nombre de carpeta"},
            {Lang::OptionsFilePrompt, "Introducir nombre de archivo"},
            {Lang::OptionsCopying, "Copiando:"},
            {Lang::PropertiesName, "Nombre: "},
            {Lang::PropertiesSize, "Tamaño: "},
            {Lang::PropertiesCreated, "Creado: "},
            {Lang::PropertiesModified, "Modificado: "},
            {Lang::PropertiesAccessed, "Accedido: "},
            {Lang::PropertiesWidth, "Ancho: "},
            {Lang::PropertiesHeight, "Alto: "},
            {Lang::DeleteMessage, "Esta acción no se puede deshacer."},
            {Lang::DeleteMultiplePrompt, "¿Desea eliminar lo siguiente:"},
            {Lang::DeletePrompt, "¿Desea eliminar "},
            {Lang::ArchiveTitle, "Extraer archivo"},
            {Lang::ArchiveMessage, "Esta acción puede tardar un poco."},
            {Lang::ArchivePrompt, "¿Desea extraer "},
            {Lang::ArchiveExtracting, "Extrayendo:"},
            {Lang::SettingsTitle, "Ajustes"},
            {Lang::SettingsSortTitle, "Ajustes de ordenación"},
            {Lang::SettingsLanguageTitle, "Idioma"},
            {Lang::SettingsUSBTitle, "USB"},
            {Lang::SettingsUSBUnmount, "Desmontar dispositivos USB"},
            {Lang::SettingsImageViewTitle, "Visor de imágenes"},
            {Lang::SettingsDevOptsTitle, "Opciones de desarrollador"},
            {Lang::SettingsMultiLangTitle, "Soporte multilingüe (desactivar para acelerar el inicio)"},
            {Lang::SettingsFullCharsetTitle, "Soporte completo de caracteres (no se puede ejecutar en modo applet)"},
            {Lang::SettingsAboutTitle, "Acerca de"},
            {Lang::SettingsCheckForUpdates, "Buscar actualizaciones"},
            {Lang::SettingsImageViewFilenameToggle, " Mostrar nombre de archivo"},
            {Lang::SettingsDevOptsLogsToggle, " Habilitar registros"},
            {Lang::SettingsMultiLangLogsToggle, " Habilitar soporte multilingüe"},
            {Lang::SettingsFullCharsetLogsToggle, " Habilitar soporte completo de caracteres"},
            {Lang::SettingsAboutVersion, "versión"},
            {Lang::SettingsAboutAuthor, "Autor"},
            {Lang::SettingsAboutBanner, "Banner"},
            {Lang::UpdateTitle, "Actualización"},
            {Lang::UpdateNetworkError, "No se pudo conectar a la red."},
            {Lang::UpdateAvailable, "Hay una actualización disponible."},
            {Lang::UpdatePrompt, "¿Desea descargar e instalar la versión NX-Shell "},
            {Lang::UpdateSuccess, "La actualización se realizó correctamente."},
            {Lang::UpdateRestart, "Por favor, salga y vuelva a ejecutar la aplicación."},
            {Lang::UpdateNotAvailable, "Está usando la última versión."},
            {Lang::USBUnmountPrompt, "¿Desea desmontar todos los dispositivos USB conectados?"},
            {Lang::USBUnmountSuccess, "El dispositivo USB ahora se puede quitar de forma segura."},
            {Lang::KeyboardEmpty, "El nombre no puede estar vacío."},
            {Lang::CommonYes, "Sí"},
            {Lang::CommonNo, "No"},
            {Lang::CommonOn, "ENCENDIDO"},
            {Lang::CommonOff, "APAGADO"},
            {Lang::TextEditorStatusLine, "Línea: "},
            {Lang::TextEditorStatusCol, "Columna: "},
            {Lang::TextEditorStatusView, "Vista: "},
            {Lang::TextEditorStatusModified, "Modificado: "},
            {Lang::TextEditorStatusSelect, "Selección: "},
            {Lang::TextEditorStatusFileSize, "Tamaño del archivo: "},
            {Lang::TextEditorStatusFileOpened, "Archivo cargado: "},
            {Lang::TextEditorEditLine, "Editar línea: "},
            {Lang::TextEditorUpdatedLine, "Línea actualizada: "},
            {Lang::TextEditorCancelEdit, "Cancelar edición"},
            {Lang::TextEditorStatusChangesUnsaved, "¡Cambios sin guardar! Presione Menos de nuevo para salir"},
            {Lang::TextEditorStatusSaved, "Guardado correctamente: "},
            {Lang::TextEditorStatusSaveFailed, "ERROR: ¡Error al guardar el archivo!"},
            {Lang::TextEditorStatusNoChangesToSave, "No hay cambios que guardar"},
            {Lang::TextEditorStatusCopiedCharacters, "Caracteres copiados: "},
            {Lang::TextEditorStatusNoTextToCopy, "No hay texto seleccionado para copiar"},
            {Lang::TextEditorStatusPasted, "Pegado desde el portapapeles"},
            {Lang::TextEditorStatusClipboardEmpty, "El portapapeles está vacío"},
            {Lang::TextEditorStatusUndoSuccessful, "Deshacer exitoso"},
            {Lang::TextEditorStatusNothingToUndo, "Nada que deshacer"},
            {Lang::TextEditorStatusRedoSuccessful, "Rehacer exitoso"},
            {Lang::TextEditorStatusNothingToRedo, "Nada que rehacer"},
            {Lang::TextEditorStatusFindText, "Buscar texto:"},
            {Lang::TextEditorStatusTextFound, "Encontrado: \""},
            {Lang::TextEditorStatusTextNotFound, "\" no encontrado"},
            {Lang::TextEditorStatusSelectModeOn, "Modo de selección ENCENDIDO"},
            {Lang::TextEditorStatusSelectModeOff, "Modo de selección APAGADO"},
            {Lang::TextEditorStatusDeletedSelectedText, "Texto seleccionado eliminado"},
            {Lang::TextEditorStatusDeletedPreCharacter, "Retroceso (carácter anterior eliminado)"},
            {Lang::TextEditorStatusDeleteForwardCharacter, "Carácter siguiente eliminado"},
            {Lang::TextEditorStatusInsertNewLine, "Nueva línea insertada"},
            {Lang::TextEditorControls, "| \uE0EF Guardar | \uE0F0 Salir | \uE0E0 Editar | \uE0E1 Eliminar | \uE0E6 Deshacer | \uE0E7 Rehacer | \uE0E4+\uE0ED/\uE0EE Seleccionar | \uE0E2 Copiar | \uE0E3 Pegar | \uE0E5 Buscar |"},
            {Lang::TextEditorExitPrompt, "El archivo es demasiado grande. Ejecuta en modo no applet!"},
        }
    },
    {
        Locale::SimplifiedChinese, {
            {Lang::ButtonOK, "确定"},
            {Lang::ButtonCancel, "取消"},
            {Lang::FileBrowser, "文件浏览器"},
            {Lang::DirectoryList, "目录列表"},
            {Lang::FileName, "文件名"},
            {Lang::FileSize, "大小"},
            {Lang::OptionsTitle, "选项"},
            {Lang::OptionsSelectAll, "全选"},
            {Lang::OptionsClearAll, "清除全部"},
            {Lang::OptionsProperties, "属性"},
            {Lang::OptionsRename, "重命名"},
            {Lang::OptionsNewFolder, "新建文件夹"},
            {Lang::OptionsNewFile, "新建文件"},
            {Lang::OptionsCopy, "复制"},
            {Lang::OptionsMove, "移动"},
            {Lang::OptionsPaste, "粘贴"},
            {Lang::OptionsDelete, "删除"},
            {Lang::OptionsSetArchiveBit, "设置存档位"},
            {Lang::OptionsRenamePrompt, "输入名称"},
            {Lang::OptionsFolderPrompt, "输入文件夹名称"},
            {Lang::OptionsFilePrompt, "输入文件名"},
            {Lang::OptionsCopying, "复制中："},
            {Lang::PropertiesName, "名称："},
            {Lang::PropertiesSize, "大小："},
            {Lang::PropertiesCreated, "创建日期："},
            {Lang::PropertiesModified, "最后修改："},
            {Lang::PropertiesAccessed, "最后访问："},
            {Lang::PropertiesWidth, "宽度："},
            {Lang::PropertiesHeight, "高度："},
            {Lang::DeleteMessage, "本操作不可逆。"},
            {Lang::DeleteMultiplePrompt, "确定删除下列文件吗？"},
            {Lang::DeletePrompt, "确定删除吗？"},
            {Lang::ArchiveTitle, "提取归档"},
            {Lang::ArchiveMessage, "本功能需要花费一点时间。"},
            {Lang::ArchivePrompt, "确定提取吗？"},
            {Lang::ArchiveExtracting, "提取中："},
            {Lang::SettingsTitle, "设置"},
            {Lang::SettingsSortTitle, "排序方式"},
            {Lang::SettingsLanguageTitle, "语言"},
            {Lang::SettingsUSBTitle, "USB"},
            {Lang::SettingsUSBUnmount, "卸载USB设备"},
            {Lang::SettingsImageViewTitle, "图片查看器"},
            {Lang::SettingsDevOptsTitle, "开发人员选项"},
            {Lang::SettingsMultiLangTitle, "多语言支持（禁用加速启动）"},
            {Lang::SettingsFullCharsetTitle, "全字符集支持（不能在小程序模式下运行）"},
            {Lang::SettingsAboutTitle, "关于"},
            {Lang::SettingsCheckForUpdates, "检查更新"},
            {Lang::SettingsImageViewFilenameToggle, " 显示文件名"},
            {Lang::SettingsDevOptsLogsToggle, " 打开日志"},
            {Lang::SettingsMultiLangLogsToggle, " 启用对多语言的支持"},
            {Lang::SettingsFullCharsetLogsToggle, " 启用对完整字符集的支持"},
            {Lang::SettingsAboutVersion, "版本"},
            {Lang::SettingsAboutAuthor, "作者"},
            {Lang::SettingsAboutBanner, "横幅"},
            {Lang::UpdateTitle, "更新"},
            {Lang::UpdateNetworkError, "连接网络失败。"},
            {Lang::UpdateAvailable, "有新版本的更新可用。"},
            {Lang::UpdatePrompt, "您希望下载并安装NX-Shell版本吗？"},
            {Lang::UpdateSuccess, "更新成功。"},
            {Lang::UpdateRestart, "请退出并重新运行应用程序。"},
            {Lang::UpdateNotAvailable, "您使用的是最新版本。"},
            {Lang::USBUnmountPrompt, "您想卸载所有连接的USB设备吗？"},
            {Lang::USBUnmountSuccess, "现在可以安全地移除USB设备。"},
            {Lang::KeyboardEmpty, "名称不能为空。"},
            {Lang::CommonYes, "是"},
            {Lang::CommonNo, "否"},
            {Lang::CommonOn, "开启"},
            {Lang::CommonOff, "关闭"},
            {Lang::TextEditorStatusLine, "行："},
            {Lang::TextEditorStatusCol, "列："},
            {Lang::TextEditorStatusView, "视图："},
            {Lang::TextEditorStatusModified, "已修改："},
            {Lang::TextEditorStatusSelect, "选择："},
            {Lang::TextEditorStatusFileSize, "文件大小: "},
            {Lang::TextEditorStatusFileOpened, "文件已加载: "},
            {Lang::TextEditorEditLine, "编辑行："},
            {Lang::TextEditorUpdatedLine, "已更新行："},
            {Lang::TextEditorCancelEdit, "取消编辑"},
            {Lang::TextEditorStatusChangesUnsaved, "未保存的更改！再次按减号退出"},
            {Lang::TextEditorStatusSaved, "保存成功："},
            {Lang::TextEditorStatusSaveFailed, "错误：保存文件失败！"},
            {Lang::TextEditorStatusNoChangesToSave, "没有要保存的更改"},
            {Lang::TextEditorStatusCopiedCharacters, "复制的字符："},
            {Lang::TextEditorStatusNoTextToCopy, "没有选定的文本可复制"},
            {Lang::TextEditorStatusPasted, "从剪贴板粘贴"},
            {Lang::TextEditorStatusClipboardEmpty, "剪贴板为空"},
            {Lang::TextEditorStatusUndoSuccessful, "撤销成功"},
            {Lang::TextEditorStatusNothingToUndo, "无可撤销操作"},
            {Lang::TextEditorStatusRedoSuccessful, "重做成功"},
            {Lang::TextEditorStatusNothingToRedo, "无可重做操作"},
            {Lang::TextEditorStatusFindText, "查找文本："},
            {Lang::TextEditorStatusTextFound, "找到：\""},
            {Lang::TextEditorStatusTextNotFound, "\" 未找到"},
            {Lang::TextEditorStatusSelectModeOn, "选择模式 开启"},
            {Lang::TextEditorStatusSelectModeOff, "选择模式 关闭"},
            {Lang::TextEditorStatusDeletedSelectedText, "已删除选定文本"},
            {Lang::TextEditorStatusDeletedPreCharacter, "退格键（已删除前一个字符）"},
            {Lang::TextEditorStatusDeleteForwardCharacter, "已删除下一个字符"},
            {Lang::TextEditorStatusInsertNewLine, "已插入新行"},
            {Lang::TextEditorControls, "| \uE0EF 保存 | \uE0F0 退出 | \uE0E0 编辑 | \uE0E1 删除 | \uE0E6 撤销 | \uE0E7 重做 | \uE0E4+\uE0ED/\uE0EE 选择 | \uE0E2 复制 | \uE0E3 粘贴 | \uE0E5 搜索 |"},
            {Lang::TextEditorExitPrompt, "文件太大，请在非Applet模式下运行！"},
        }
    },
    {
        Locale::Korean, {
            {Lang::ButtonOK, "확인"},
            {Lang::ButtonCancel, "취소"},
            {Lang::FileBrowser, "파일 브라우저"},
            {Lang::DirectoryList, "디렉토리 목록"},
            {Lang::FileName, "파일명"},
            {Lang::FileSize, "크기"},
            {Lang::OptionsTitle, "옵션"},
            {Lang::OptionsSelectAll, "모두 선택"},
            {Lang::OptionsClearAll, "모두 지우기"},
            {Lang::OptionsProperties, "속성"},
            {Lang::OptionsRename, "이름 바꾸기"},
            {Lang::OptionsNewFolder, "새 폴더"},
            {Lang::OptionsNewFile, "새 파일"},
            {Lang::OptionsCopy, "복사"},
            {Lang::OptionsMove, "이동"},
            {Lang::OptionsPaste, "붙여넣기"},
            {Lang::OptionsDelete, "삭제"},
            {Lang::OptionsSetArchiveBit, "아카이브 비트 설정"},
            {Lang::OptionsRenamePrompt, "이름 입력"},
            {Lang::OptionsFolderPrompt, "폴더 이름 입력"},
            {Lang::OptionsFilePrompt, "파일 이름 입력"},
            {Lang::OptionsCopying, "복사 중:"},
            {Lang::PropertiesName, "이름: "},
            {Lang::PropertiesSize, "크기: "},
            {Lang::PropertiesCreated, "생성일: "},
            {Lang::PropertiesModified, "수정일: "},
            {Lang::PropertiesAccessed, "접근일: "},
            {Lang::PropertiesWidth, "너비: "},
            {Lang::PropertiesHeight, "높이: "},
            {Lang::DeleteMessage, "이 작업은 취소할 수 없습니다."},
            {Lang::DeleteMultiplePrompt, "다음을 삭제하시겠습니까:"},
            {Lang::DeletePrompt, "삭제하시겠습니까 "},
            {Lang::ArchiveTitle, "아카이브 추출"},
            {Lang::ArchiveMessage, "이 작업은 시간이 걸릴 수 있습니다."},
            {Lang::ArchivePrompt, "추출하시겠습니까 "},
            {Lang::ArchiveExtracting, "추출 중:"},
            {Lang::SettingsTitle, "설정"},
            {Lang::SettingsSortTitle, "정렬 설정"},
            {Lang::SettingsLanguageTitle, "언어"},
            {Lang::SettingsUSBTitle, "USB"},
            {Lang::SettingsUSBUnmount, "USB 장치 마운트 해제"},
            {Lang::SettingsImageViewTitle, "이미지 뷰어"},
            {Lang::SettingsDevOptsTitle, "개발자 옵션"},
            {Lang::SettingsMultiLangTitle, "다국어 지원 (시작 속도를 높이려면 비활성화)"},
            {Lang::SettingsFullCharsetTitle, "전체 문자 집합 지원 (애플릿 모드에서는 실행 불가)"},
            {Lang::SettingsAboutTitle, "정보"},
            {Lang::SettingsCheckForUpdates, "업데이트 확인"},
            {Lang::SettingsImageViewFilenameToggle, " 파일명 표시"},
            {Lang::SettingsDevOptsLogsToggle, " 로그 활성화"},
            {Lang::SettingsMultiLangLogsToggle, " 다국어 지원 활성화"},
            {Lang::SettingsFullCharsetLogsToggle, " 전체 문자 집합 지원 활성화"},
            {Lang::SettingsAboutVersion, "버전"},
            {Lang::SettingsAboutAuthor, "제작자"},
            {Lang::SettingsAboutBanner, "배너"},
            {Lang::UpdateTitle, "업데이트"},
            {Lang::UpdateNetworkError, "네트워크에 연결할 수 없습니다."},
            {Lang::UpdateAvailable, "업데이트가 가능합니다."},
            {Lang::UpdatePrompt, "NX-Shell 버전을 다운로드하고 설치하시겠습니까 "},
            {Lang::UpdateSuccess, "업데이트에 성공했습니다."},
            {Lang::UpdateRestart, "애플리케이션을 종료하고 다시 실행해 주세요."},
            {Lang::UpdateNotAvailable, "최신 버전을 사용 중입니다."},
            {Lang::USBUnmountPrompt, "연결된 모든 USB 장치의 마운트를 해제하시겠습니까?"},
            {Lang::USBUnmountSuccess, "이제 USB 장치를 안전하게 제거할 수 있습니다."},
            {Lang::KeyboardEmpty, "이름은 비어 있을 수 없습니다."},
            {Lang::CommonYes, "예"},
            {Lang::CommonNo, "아니오"},
            {Lang::CommonOn, "켬"},
            {Lang::CommonOff, "끔"},
            {Lang::TextEditorStatusLine, "줄: "},
            {Lang::TextEditorStatusCol, "열: "},
            {Lang::TextEditorStatusView, "보기: "},
            {Lang::TextEditorStatusModified, "수정됨: "},
            {Lang::TextEditorStatusSelect, "선택: "},
            {Lang::TextEditorStatusFileSize, "파일 크기: "},
            {Lang::TextEditorStatusFileOpened, "파일 로드 완료: "},
            {Lang::TextEditorEditLine, "줄 편집: "},
            {Lang::TextEditorUpdatedLine, "줄 업데이트: "},
            {Lang::TextEditorCancelEdit, "편집 취소"},
            {Lang::TextEditorStatusChangesUnsaved, "저장하지 않은 변경 사항! 종료하려면 마이너스 키를 다시 누르세요"},
            {Lang::TextEditorStatusSaved, "성공적으로 저장됨: "},
            {Lang::TextEditorStatusSaveFailed, "오류: 파일 저장 실패!"},
            {Lang::TextEditorStatusNoChangesToSave, "저장할 변경 사항 없음"},
            {Lang::TextEditorStatusCopiedCharacters, "복사된 문자: "},
            {Lang::TextEditorStatusNoTextToCopy, "복사할 텍스트가 선택되지 않음"},
            {Lang::TextEditorStatusPasted, "클립보드에서 붙여넣기"},
            {Lang::TextEditorStatusClipboardEmpty, "클립보드가 비어 있음"},
            {Lang::TextEditorStatusUndoSuccessful, "실행 취소 성공"},
            {Lang::TextEditorStatusNothingToUndo, "실행 취소할 항목 없음"},
            {Lang::TextEditorStatusRedoSuccessful, "다시 실행 성공"},
            {Lang::TextEditorStatusNothingToRedo, "다시 실행할 항목 없음"},
            {Lang::TextEditorStatusFindText, "텍스트 찾기:"},
            {Lang::TextEditorStatusTextFound, "찾음: \""},
            {Lang::TextEditorStatusTextNotFound, "\" 찾을 수 없음"},
            {Lang::TextEditorStatusSelectModeOn, "선택 모드 켜짐"},
            {Lang::TextEditorStatusSelectModeOff, "선택 모드 끔"},
            {Lang::TextEditorStatusDeletedSelectedText, "선택한 텍스트 삭제됨"},
            {Lang::TextEditorStatusDeletedPreCharacter, "백스페이스 (이전 문자 삭제됨)"},
            {Lang::TextEditorStatusDeleteForwardCharacter, "다음 문자 삭제됨"},
            {Lang::TextEditorStatusInsertNewLine, "새 줄 삽입됨"},
            {Lang::TextEditorControls, "| \uE0EF 저장 | \uE0F0 종료 | \uE0E0 편집 | \uE0E1 삭제 | \uE0E6 실행 취소 | \uE0E7 다시 실행 | \uE0E4+\uE0ED/\uE0EE 선택 | \uE0E2 복사 | \uE0E3 붙여넣기 | \uE0E5 검색 |"},
            {Lang::TextEditorExitPrompt, "파일이 너무 큽니다. 애플릿 모드가 아닌 모드에서 실행하세요!"},
        }
    },
    {
        Locale::Dutch, {
            {Lang::ButtonOK, "OK"},
            {Lang::ButtonCancel, "Annuleren"},
            {Lang::FileBrowser, "Bestandsbeheerder"},
            {Lang::DirectoryList, "Maplijst"},
            {Lang::FileName, "Bestandsnaam"},
            {Lang::FileSize, "Grootte"},
            {Lang::OptionsTitle, "Opties"},
            {Lang::OptionsSelectAll, "Alles selecteren"},
            {Lang::OptionsClearAll, "Alles wissen"},
            {Lang::OptionsProperties, "Eigenschappen"},
            {Lang::OptionsRename, "Naam wijzigen"},
            {Lang::OptionsNewFolder, "Nieuwe map"},
            {Lang::OptionsNewFile, "Nieuw bestand"},
            {Lang::OptionsCopy, "Kopiëren"},
            {Lang::OptionsMove, "Verplaatsen"},
            {Lang::OptionsPaste, "Plakken"},
            {Lang::OptionsDelete, "Verwijderen"},
            {Lang::OptionsSetArchiveBit, "Stel archiefbit in"},
            {Lang::OptionsRenamePrompt, "Voer naam in"},
            {Lang::OptionsFolderPrompt, "Voer mapnaam in"},
            {Lang::OptionsFilePrompt, "Voer bestandsnaam in"},
            {Lang::OptionsCopying, "Kopiëren:"},
            {Lang::PropertiesName, "Naam: "},
            {Lang::PropertiesSize, "Grootte: "},
            {Lang::PropertiesCreated, "Aangemaakt: "},
            {Lang::PropertiesModified, "Gewijzigd: "},
            {Lang::PropertiesAccessed, "Geopend: "},
            {Lang::PropertiesWidth, "Breedte: "},
            {Lang::PropertiesHeight, "Hoogte: "},
            {Lang::DeleteMessage, "Deze actie kan niet ongedaan worden gemaakt."},
            {Lang::DeleteMultiplePrompt, "Wilt u het volgende verwijderen:"},
            {Lang::DeletePrompt, "Wilt u verwijderen "},
            {Lang::ArchiveTitle, "Archief uitpakken"},
            {Lang::ArchiveMessage, "Deze actie kan even duren."},
            {Lang::ArchivePrompt, "Wilt u uitpakken "},
            {Lang::ArchiveExtracting, "Uitpakken:"},
            {Lang::SettingsTitle, "Instellingen"},
            {Lang::SettingsSortTitle, "Sorteerinstellingen"},
            {Lang::SettingsLanguageTitle, "Taal"},
            {Lang::SettingsUSBTitle, "USB"},
            {Lang::SettingsUSBUnmount, "USB-apparaten ontkoppelen"},
            {Lang::SettingsImageViewTitle, "Afbeeldingsweergave"},
            {Lang::SettingsDevOptsTitle, "Ontwikkelaarsopties"},
            {Lang::SettingsMultiLangTitle, "Meertalige ondersteuning (uitschakelen om opstarten te versnellen)"},
            {Lang::SettingsFullCharsetTitle, "Volledige tekensetondersteuning (kan niet in appletmodus worden uitgevoerd)"},
            {Lang::SettingsAboutTitle, "Over"},
            {Lang::SettingsCheckForUpdates, "Controleren op updates"},
            {Lang::SettingsImageViewFilenameToggle, " Bestandsnaam weergeven"},
            {Lang::SettingsDevOptsLogsToggle, " Logboeken inschakelen"},
            {Lang::SettingsMultiLangLogsToggle, " Ondersteuning voor meerdere talen inschakelen"},
            {Lang::SettingsFullCharsetLogsToggle, " Ondersteuning voor volledige tekenset inschakelen"},
            {Lang::SettingsAboutVersion, "versie"},
            {Lang::SettingsAboutAuthor, "Auteur"},
            {Lang::SettingsAboutBanner, "Banner"},
            {Lang::UpdateTitle, "Update"},
            {Lang::UpdateNetworkError, "Kan geen verbinding maken met het netwerk."},
            {Lang::UpdateAvailable, "Er is een update beschikbaar."},
            {Lang::UpdatePrompt, "Wilt u NX-Shell-versie downloaden en installeren "},
            {Lang::UpdateSuccess, "Update is geslaagd."},
            {Lang::UpdateRestart, "Sluit af en voer de applicatie opnieuw uit."},
            {Lang::UpdateNotAvailable, "U gebruikt de nieuwste versie."},
            {Lang::USBUnmountPrompt, "Wilt u alle verbonden USB-apparaten ontkoppelen?"},
            {Lang::USBUnmountSuccess, "Het USB-apparaat kan nu veilig worden verwijderd."},
            {Lang::KeyboardEmpty, "De naam mag niet leeg zijn."},
            {Lang::CommonYes, "Ja"},
            {Lang::CommonNo, "Nee"},
            {Lang::CommonOn, "AAN"},
            {Lang::CommonOff, "UIT"},
            {Lang::TextEditorStatusLine, "Regel: "},
            {Lang::TextEditorStatusCol, "Kolom: "},
            {Lang::TextEditorStatusView, "Weergave: "},
            {Lang::TextEditorStatusModified, "Gewijzigd: "},
            {Lang::TextEditorStatusSelect, "Selectie: "},
            {Lang::TextEditorStatusFileSize, "Bestandsgrootte: "},
            {Lang::TextEditorStatusFileOpened, "Bestand geladen: "},
            {Lang::TextEditorEditLine, "Regel bewerken: "},
            {Lang::TextEditorUpdatedLine, "Regel bijgewerkt: "},
            {Lang::TextEditorCancelEdit, "Bewerking annuleren"},
            {Lang::TextEditorStatusChangesUnsaved, "Niet-opgeslagen wijzigingen! Druk opnieuw op Min om af te sluiten"},
            {Lang::TextEditorStatusSaved, "Succesvol opgeslagen: "},
            {Lang::TextEditorStatusSaveFailed, "FOUT: Kan bestand niet opslaan!"},
            {Lang::TextEditorStatusNoChangesToSave, "Geen wijzigingen om op te slaan"},
            {Lang::TextEditorStatusCopiedCharacters, "Gekopieerde tekens: "},
            {Lang::TextEditorStatusNoTextToCopy, "Geen tekst geselecteerd om te kopiëren"},
            {Lang::TextEditorStatusPasted, "Geplakt van klembord"},
            {Lang::TextEditorStatusClipboardEmpty, "Klembord is leeg"},
            {Lang::TextEditorStatusUndoSuccessful, "Ongedaan maken succesvol"},
            {Lang::TextEditorStatusNothingToUndo, "Niets om ongedaan te maken"},
            {Lang::TextEditorStatusRedoSuccessful, "Opnieuw succesvol"},
            {Lang::TextEditorStatusNothingToRedo, "Niets om opnieuw te doen"},
            {Lang::TextEditorStatusFindText, "Tekst zoeken:"},
            {Lang::TextEditorStatusTextFound, "Gevonden: \""},
            {Lang::TextEditorStatusTextNotFound, "\" niet gevonden"},
            {Lang::TextEditorStatusSelectModeOn, "Selectiemodus AAN"},
            {Lang::TextEditorStatusSelectModeOff, "Selectiemodus UIT"},
            {Lang::TextEditorStatusDeletedSelectedText, "Geselecteerde tekst verwijderd"},
            {Lang::TextEditorStatusDeletedPreCharacter, "Backspace (vorig teken verwijderd)"},
            {Lang::TextEditorStatusDeleteForwardCharacter, "Volgend teken verwijderd"},
            {Lang::TextEditorStatusInsertNewLine, "Nieuwe regel ingevoegd"},
            {Lang::TextEditorControls, "| \uE0EF Opslaan | \uE0F0 Afsluiten | \uE0E0 Bewerken | \uE0E1 Verwijderen | \uE0E6 Ongedaan maken | \uE0E7 Opnieuw | \uE0E4+\uE0ED/\uE0EE Selecteren | \uE0E2 Kopiëren | \uE0E3 Plakken | \uE0E5 Zoeken |"},
            {Lang::TextEditorExitPrompt, "Bestand is te groot. Voer uit in niet-appletmodus!"},
        }
    },
    {
        Locale::Portuguese, {
            {Lang::ButtonOK, "OK"},
            {Lang::ButtonCancel, "Cancelar"},
            {Lang::FileBrowser, "Navegador de Arquivos"},
            {Lang::DirectoryList, "Lista de Diretórios"},
            {Lang::FileName, "Nome do Arquivo"},
            {Lang::FileSize, "Tamanho"},
            {Lang::OptionsTitle, "Opções"},
            {Lang::OptionsSelectAll, "Selecionar Tudo"},
            {Lang::OptionsClearAll, "Limpar Tudo"},
            {Lang::OptionsProperties, "Propriedades"},
            {Lang::OptionsRename, "Renomear"},
            {Lang::OptionsNewFolder, "Nova Pasta"},
            {Lang::OptionsNewFile, "Novo Arquivo"},
            {Lang::OptionsCopy, "Copiar"},
            {Lang::OptionsMove, "Mover"},
            {Lang::OptionsPaste, "Colar"},
            {Lang::OptionsDelete, "Excluir"},
            {Lang::OptionsSetArchiveBit, "Definir Bit de Arquivo"},
            {Lang::OptionsRenamePrompt, "Digite o nome"},
            {Lang::OptionsFolderPrompt, "Digite o nome da pasta"},
            {Lang::OptionsFilePrompt, "Digite o nome do arquivo"},
            {Lang::OptionsCopying, "Copiando:"},
            {Lang::PropertiesName, "Nome: "},
            {Lang::PropertiesSize, "Tamanho: "},
            {Lang::PropertiesCreated, "Criado: "},
            {Lang::PropertiesModified, "Modificado: "},
            {Lang::PropertiesAccessed, "Acessado: "},
            {Lang::PropertiesWidth, "Largura: "},
            {Lang::PropertiesHeight, "Altura: "},
            {Lang::DeleteMessage, "Essa ação não pode ser desfeita."},
            {Lang::DeleteMultiplePrompt, "Deseja excluir o seguinte:"},
            {Lang::DeletePrompt, "Deseja excluir "},
            {Lang::ArchiveTitle, "Extrair arquivo"},
            {Lang::ArchiveMessage, "Essa ação pode demorar um pouco."},
            {Lang::ArchivePrompt, "Deseja extrair "},
            {Lang::ArchiveExtracting, "Extraindo:"},
            {Lang::SettingsTitle, "Configurações"},
            {Lang::SettingsSortTitle, "Configurações de Ordenação"},
            {Lang::SettingsLanguageTitle, "Idioma"},
            {Lang::SettingsUSBTitle, "USB"},
            {Lang::SettingsUSBUnmount, "Desmontar Dispositivos USB"},
            {Lang::SettingsImageViewTitle, "Visualizador de Imagens"},
            {Lang::SettingsDevOptsTitle, "Opções do Desenvolvedor"},
            {Lang::SettingsMultiLangTitle, "Suporte multilíngue (desative para acelerar a inicialização)"},
            {Lang::SettingsFullCharsetTitle, "Suporte ao conjunto de caracteres completo (não pode ser executado no modo applet)"},
            {Lang::SettingsAboutTitle, "Sobre"},
            {Lang::SettingsCheckForUpdates, "Verificar Atualizações"},
            {Lang::SettingsImageViewFilenameToggle, " Exibir nome do arquivo"},
            {Lang::SettingsDevOptsLogsToggle, " Ativar logs"},
            {Lang::SettingsMultiLangLogsToggle, " Ativar suporte multilíngue"},
            {Lang::SettingsFullCharsetLogsToggle, " Ativar suporte ao conjunto de caracteres completo"},
            {Lang::SettingsAboutVersion, "versão"},
            {Lang::SettingsAboutAuthor, "Autor"},
            {Lang::SettingsAboutBanner, "Banner"},
            {Lang::UpdateTitle, "Atualização"},
            {Lang::UpdateNetworkError, "Não foi possível conectar-se à rede."},
            {Lang::UpdateAvailable, "Uma atualização está disponível."},
            {Lang::UpdatePrompt, "Deseja baixar e instalar a versão NX-Shell "},
            {Lang::UpdateSuccess, "Atualização bem-sucedida."},
            {Lang::UpdateRestart, "Por favor, saia e reinicie o aplicativo."},
            {Lang::UpdateNotAvailable, "Você está na versão mais recente."},
            {Lang::USBUnmountPrompt, "Deseja desmontar todos os dispositivos USB conectados?"},
            {Lang::USBUnmountSuccess, "O dispositivo USB agora pode ser removido com segurança."},
            {Lang::KeyboardEmpty, "O nome não pode estar vazio."},
            {Lang::CommonYes, "Sim"},
            {Lang::CommonNo, "Não"},
            {Lang::CommonOn, "LIGADO"},
            {Lang::CommonOff, "DESLIGADO"},
            {Lang::TextEditorStatusLine, "Linha: "},
            {Lang::TextEditorStatusCol, "Coluna: "},
            {Lang::TextEditorStatusView, "Visualização: "},
            {Lang::TextEditorStatusModified, "Modificado: "},
            {Lang::TextEditorStatusSelect, "Seleção: "},
            {Lang::TextEditorStatusFileSize, "Tamanho do arquivo: "},
            {Lang::TextEditorStatusFileOpened, "Arquivo carregado: "},
            {Lang::TextEditorEditLine, "Editar linha: "},
            {Lang::TextEditorUpdatedLine, "Linha atualizada: "},
            {Lang::TextEditorCancelEdit, "Cancelar edição"},
            {Lang::TextEditorStatusChangesUnsaved, "Alterações não salvas! Pressione Menos novamente para sair"},
            {Lang::TextEditorStatusSaved, "Salvo com sucesso: "},
            {Lang::TextEditorStatusSaveFailed, "ERRO: Falha ao salvar o arquivo!"},
            {Lang::TextEditorStatusNoChangesToSave, "Nenhuma alteração para salvar"},
            {Lang::TextEditorStatusCopiedCharacters, "Caracteres copiados: "},
            {Lang::TextEditorStatusNoTextToCopy, "Nenhum texto selecionado para copiar"},
            {Lang::TextEditorStatusPasted, "Colado da área de transferência"},
            {Lang::TextEditorStatusClipboardEmpty, "Área de transferência vazia"},
            {Lang::TextEditorStatusUndoSuccessful, "Desfazer bem-sucedido"},
            {Lang::TextEditorStatusNothingToUndo, "Nada para desfazer"},
            {Lang::TextEditorStatusRedoSuccessful, "Refazer bem-sucedido"},
            {Lang::TextEditorStatusNothingToRedo, "Nada para refazer"},
            {Lang::TextEditorStatusFindText, "Localizar texto:"},
            {Lang::TextEditorStatusTextFound, "Encontrado: \""},
            {Lang::TextEditorStatusTextNotFound, "\" não encontrado"},
            {Lang::TextEditorStatusSelectModeOn, "Modo de seleção LIGADO"},
            {Lang::TextEditorStatusSelectModeOff, "Modo de seleção DESLIGADO"},
            {Lang::TextEditorStatusDeletedSelectedText, "Texto selecionado excluído"},
            {Lang::TextEditorStatusDeletedPreCharacter, "Backspace (caractere anterior excluído)"},
            {Lang::TextEditorStatusDeleteForwardCharacter, "Próximo caractere excluído"},
            {Lang::TextEditorStatusInsertNewLine, "Nova linha inserida"},
            {Lang::TextEditorControls, "| \uE0EF Salvar | \uE0F0 Sair | \uE0E0 Editar | \uE0E1 Excluir | \uE0E6 Desfazer | \uE0E7 Refazer | \uE0E4+\uE0ED/\uE0EE Selecionar | \uE0E2 Copiar | \uE0E3 Colar | \uE0E5 Pesquisar |"},
            {Lang::TextEditorExitPrompt, "O arquivo é muito grande. Execute no modo não applet!"},
        }
    },
    {
        Locale::Russian, {
            {Lang::ButtonOK, "OK"},
            {Lang::ButtonCancel, "Отмена"},
            {Lang::FileBrowser, "Файловый браузер"},
            {Lang::DirectoryList, "Список директорий"},
            {Lang::FileName, "Имя файла"},
            {Lang::FileSize, "Размер"},
            {Lang::OptionsTitle, "Опции"},
            {Lang::OptionsSelectAll, "Выбрать всё"},
            {Lang::OptionsClearAll, "Очистить всё"},
            {Lang::OptionsProperties, "Свойства"},
            {Lang::OptionsRename, "Переименовать"},
            {Lang::OptionsNewFolder, "Новая папка"},
            {Lang::OptionsNewFile, "Новый файл"},
            {Lang::OptionsCopy, "Копировать"},
            {Lang::OptionsMove, "Переместить"},
            {Lang::OptionsPaste, "Вставить"},
            {Lang::OptionsDelete, "Удалить"},
            {Lang::OptionsSetArchiveBit, "Установить бит архива"},
            {Lang::OptionsRenamePrompt, "Введите имя"},
            {Lang::OptionsFolderPrompt, "Введите имя папки"},
            {Lang::OptionsFilePrompt, "Введите имя файла"},
            {Lang::OptionsCopying, "Копирование:"},
            {Lang::PropertiesName, "Имя: "},
            {Lang::PropertiesSize, "Размер: "},
            {Lang::PropertiesCreated, "Создан: "},
            {Lang::PropertiesModified, "Изменён: "},
            {Lang::PropertiesAccessed, "Доступ: "},
            {Lang::PropertiesWidth, "Ширина: "},
            {Lang::PropertiesHeight, "Высота: "},
            {Lang::DeleteMessage, "Это действие невозможно отменить."},
            {Lang::DeleteMultiplePrompt, "Вы хотите удалить следующее:"},
            {Lang::DeletePrompt, "Вы хотите удалить "},
            {Lang::ArchiveTitle, "Извлечь архив"},
            {Lang::ArchiveMessage, "Это действие может занять некоторое время."},
            {Lang::ArchivePrompt, "Вы хотите извлечь "},
            {Lang::ArchiveExtracting, "Извлечение:"},
            {Lang::SettingsTitle, "Настройки"},
            {Lang::SettingsSortTitle, "Настройки сортировки"},
            {Lang::SettingsLanguageTitle, "Язык"},
            {Lang::SettingsUSBTitle, "USB"},
            {Lang::SettingsUSBUnmount, "Отключить USB-устройства"},
            {Lang::SettingsImageViewTitle, "Просмотр изображений"},
            {Lang::SettingsDevOptsTitle, "Опции разработчика"},
            {Lang::SettingsMultiLangTitle, "Многоязычная поддержка (отключите для ускорения запуска)"},
            {Lang::SettingsFullCharsetTitle, "Поддержка полного набора символов (не может работать в режиме апплета)"},
            {Lang::SettingsAboutTitle, "О программе"},
            {Lang::SettingsCheckForUpdates, "Проверить обновления"},
            {Lang::SettingsImageViewFilenameToggle, " Отобразить имя файла"},
            {Lang::SettingsDevOptsLogsToggle, " Включить журналы"},
            {Lang::SettingsMultiLangLogsToggle, " Включить поддержку многоязычности"},
            {Lang::SettingsFullCharsetLogsToggle, " Включить поддержку полного набора символов"},
            {Lang::SettingsAboutVersion, "версия"},
            {Lang::SettingsAboutAuthor, "Автор"},
            {Lang::SettingsAboutBanner, "Баннер"},
            {Lang::UpdateTitle, "Обновление"},
            {Lang::UpdateNetworkError, "Не удалось подключиться к сети."},
            {Lang::UpdateAvailable, "Доступно обновление."},
            {Lang::UpdatePrompt, "Вы хотите загрузить и установить версию NX-Shell "},
            {Lang::UpdateSuccess, "Обновление прошло успешно."},
            {Lang::UpdateRestart, "Пожалуйста, выйдите и перезапустите приложение."},
            {Lang::UpdateNotAvailable, "Вы используете последнюю версию."},
            {Lang::USBUnmountPrompt, "Вы хотите отключить все подключенные USB-устройства?"},
            {Lang::USBUnmountSuccess, "Теперь USB-устройство можно безопасно извлечь."},
            {Lang::KeyboardEmpty, "Имя не может быть пустым."},
            {Lang::CommonYes, "Да"},
            {Lang::CommonNo, "Нет"},
            {Lang::CommonOn, "ВКЛ"},
            {Lang::CommonOff, "ВЫКЛ"},
            {Lang::TextEditorStatusLine, "Строка: "},
            {Lang::TextEditorStatusCol, "Столбец: "},
            {Lang::TextEditorStatusView, "Вид: "},
            {Lang::TextEditorStatusModified, "Изменено: "},
            {Lang::TextEditorStatusSelect, "Выделение: "},
            {Lang::TextEditorStatusFileSize, "Размер файла: "},
            {Lang::TextEditorStatusFileOpened, "Файл загружен: "},
            {Lang::TextEditorEditLine, "Редактировать строку: "},
            {Lang::TextEditorUpdatedLine, "Строка обновлена: "},
            {Lang::TextEditorCancelEdit, "Отменить редактирование"},
            {Lang::TextEditorStatusChangesUnsaved, "Несохранённые изменения! Нажмите Минус ещё раз для выхода"},
            {Lang::TextEditorStatusSaved, "Успешно сохранено: "},
            {Lang::TextEditorStatusSaveFailed, "ОШИБКА: Не удалось сохранить файл!"},
            {Lang::TextEditorStatusNoChangesToSave, "Нет изменений для сохранения"},
            {Lang::TextEditorStatusCopiedCharacters, "Скопированные символы: "},
            {Lang::TextEditorStatusNoTextToCopy, "Нет выделенного текста для копирования"},
            {Lang::TextEditorStatusPasted, "Вставлено из буфера обмена"},
            {Lang::TextEditorStatusClipboardEmpty, "Буфер обмена пуст"},
            {Lang::TextEditorStatusUndoSuccessful, "Отмена выполнена успешно"},
            {Lang::TextEditorStatusNothingToUndo, "Нечего отменять"},
            {Lang::TextEditorStatusRedoSuccessful, "Повтор выполнен успешно"},
            {Lang::TextEditorStatusNothingToRedo, "Нечего повторять"},
            {Lang::TextEditorStatusFindText, "Найти текст:"},
            {Lang::TextEditorStatusTextFound, "Найдено: \""},
            {Lang::TextEditorStatusTextNotFound, "\" не найдено"},
            {Lang::TextEditorStatusSelectModeOn, "Режим выделения ВКЛ"},
            {Lang::TextEditorStatusSelectModeOff, "Режим выделения ВЫКЛ"},
            {Lang::TextEditorStatusDeletedSelectedText, "Выделенный текст удалён"},
            {Lang::TextEditorStatusDeletedPreCharacter, "Backspace (удалён предыдущий символ)"},
            {Lang::TextEditorStatusDeleteForwardCharacter, "Удалён следующий символ"},
            {Lang::TextEditorStatusInsertNewLine, "Вставлена новая строка"},
            {Lang::TextEditorControls, "| \uE0EF Сохранить | \uE0F0 Выйти | \uE0E0 Редактировать | \uE0E1 Удалить | \uE0E6 Отменить | \uE0E7 Повторить | \uE0E4+\uE0ED/\uE0EE Выделить | \uE0E2 Копировать | \uE0E3 Вставить | \uE0E5 Найти |"},
            {Lang::TextEditorExitPrompt, "Файл слишком большой. Запустите в неапплетном режиме!"},
        }
    },
    {
        Locale::TraditionalChinese, {
            {Lang::ButtonOK, "確定"},
            {Lang::ButtonCancel, "取消"},
            {Lang::FileBrowser, "檔案瀏覽器"},
            {Lang::DirectoryList, "目錄清單"},
            {Lang::FileName, "檔名"},
            {Lang::FileSize, "大小"},
            {Lang::OptionsTitle, "選項"},
            {Lang::OptionsSelectAll, "全選"},
            {Lang::OptionsClearAll, "清除全部"},
            {Lang::OptionsProperties, "屬性"},
            {Lang::OptionsRename, "重新命名"},
            {Lang::OptionsNewFolder, "新建資料夾"},
            {Lang::OptionsNewFile, "新建檔案"},
            {Lang::OptionsCopy, "複製"},
            {Lang::OptionsMove, "移動"},
            {Lang::OptionsPaste, "貼上"},
            {Lang::OptionsDelete, "刪除"},
            {Lang::OptionsSetArchiveBit, "設定存檔位"},
            {Lang::OptionsRenamePrompt, "輸入名稱"},
            {Lang::OptionsFolderPrompt, "輸入資料夾名稱"},
            {Lang::OptionsFilePrompt, "輸入檔名"},
            {Lang::OptionsCopying, "複製中："},
            {Lang::PropertiesName, "名稱："},
            {Lang::PropertiesSize, "大小："},
            {Lang::PropertiesCreated, "建立日期："},
            {Lang::PropertiesModified, "最後修改："},
            {Lang::PropertiesAccessed, "最後訪問："},
            {Lang::PropertiesWidth, "寬度："},
            {Lang::PropertiesHeight, "高度："},
            {Lang::DeleteMessage, "本操作不可逆。"},
            {Lang::DeleteMultiplePrompt, "確定刪除下列檔案嗎？"},
            {Lang::DeletePrompt, "確定刪除嗎？"},
            {Lang::ArchiveTitle, "解壓歸檔"},
            {Lang::ArchiveMessage, "本功能需要花費一點時間。"},
            {Lang::ArchivePrompt, "確定解壓嗎？"},
            {Lang::ArchiveExtracting, "解壓中："},
            {Lang::SettingsTitle, "設定"},
            {Lang::SettingsSortTitle, "排序方式"},
            {Lang::SettingsLanguageTitle, "語言"},
            {Lang::SettingsUSBTitle, "USB"},
            {Lang::SettingsUSBUnmount, "卸載USB裝置"},
            {Lang::SettingsImageViewTitle, "圖片檢視器"},
            {Lang::SettingsDevOptsTitle, "開發人員選項"},
            {Lang::SettingsMultiLangTitle, "多語言支援（停用加速啟動）"},
            {Lang::SettingsFullCharsetTitle, "全字元集支援（不能在小程式模式下執行）"},
            {Lang::SettingsAboutTitle, "關於"},
            {Lang::SettingsCheckForUpdates, "檢查更新"},
            {Lang::SettingsImageViewFilenameToggle, " 顯示檔名"},
            {Lang::SettingsDevOptsLogsToggle, " 啟用日誌"},
            {Lang::SettingsMultiLangLogsToggle, " 啟用對多語言的支援"},
            {Lang::SettingsFullCharsetLogsToggle, " 啟用對完整字元集的支援"},
            {Lang::SettingsAboutVersion, "版本"},
            {Lang::SettingsAboutAuthor, "作者"},
            {Lang::SettingsAboutBanner, "橫幅"},
            {Lang::UpdateTitle, "更新"},
            {Lang::UpdateNetworkError, "連接網路失敗。"},
            {Lang::UpdateAvailable, "有新版本的更新可用。"},
            {Lang::UpdatePrompt, "您希望下載並安裝NX-Shell版本嗎？"},
            {Lang::UpdateSuccess, "更新成功。"},
            {Lang::UpdateRestart, "請退出並重新執行應用程式。"},
            {Lang::UpdateNotAvailable, "您使用的是最新版本。"},
            {Lang::USBUnmountPrompt, "您想卸載所有連接的USB裝置嗎？"},
            {Lang::USBUnmountSuccess, "現在可以安全地移除USB裝置。"},
            {Lang::KeyboardEmpty, "名稱不能為空。"},
            {Lang::CommonYes, "是"},
            {Lang::CommonNo, "否"},
            {Lang::CommonOn, "開啟"},
            {Lang::CommonOff, "關閉"},
            {Lang::TextEditorStatusLine, "行："},
            {Lang::TextEditorStatusCol, "列："},
            {Lang::TextEditorStatusView, "檢視："},
            {Lang::TextEditorStatusModified, "已修改："},
            {Lang::TextEditorStatusSelect, "選擇："},
            {Lang::TextEditorStatusFileSize, "檔案大小："},
            {Lang::TextEditorStatusFileOpened, "檔案已載入: "},
            {Lang::TextEditorEditLine, "編輯行："},
            {Lang::TextEditorUpdatedLine, "已更新行："},
            {Lang::TextEditorCancelEdit, "取消編輯"},
            {Lang::TextEditorStatusChangesUnsaved, "未儲存的更改！再次按減號退出"},
            {Lang::TextEditorStatusSaved, "儲存成功："},
            {Lang::TextEditorStatusSaveFailed, "錯誤：儲存檔案失敗！"},
            {Lang::TextEditorStatusNoChangesToSave, "沒有要儲存的更改"},
            {Lang::TextEditorStatusCopiedCharacters, "複製的字元："},
            {Lang::TextEditorStatusNoTextToCopy, "沒有選定的文字可複製"},
            {Lang::TextEditorStatusPasted, "從剪貼簿貼上"},
            {Lang::TextEditorStatusClipboardEmpty, "剪貼簿為空"},
            {Lang::TextEditorStatusUndoSuccessful, "復原成功"},
            {Lang::TextEditorStatusNothingToUndo, "無可復原操作"},
            {Lang::TextEditorStatusRedoSuccessful, "重做成功"},
            {Lang::TextEditorStatusNothingToRedo, "無可重做操作"},
            {Lang::TextEditorStatusFindText, "尋找文字："},
            {Lang::TextEditorStatusTextFound, "找到：\""},
            {Lang::TextEditorStatusTextNotFound, "\" 未找到"},
            {Lang::TextEditorStatusSelectModeOn, "選擇模式 開啟"},
            {Lang::TextEditorStatusSelectModeOff, "選擇模式 關閉"},
            {Lang::TextEditorStatusDeletedSelectedText, "已刪除選定文字"},
            {Lang::TextEditorStatusDeletedPreCharacter, "退格鍵（已刪除前一個字元）"},
            {Lang::TextEditorStatusDeleteForwardCharacter, "已刪除下一個字元"},
            {Lang::TextEditorStatusInsertNewLine, "已插入新行"},
            {Lang::TextEditorControls, "| \uE0EF 儲存 | \uE0F0 退出 | \uE0E0 編輯 | \uE0E1 刪除 | \uE0E6 復原 | \uE0E7 重做 | \uE0E4+\uE0ED/\uE0EE 選擇 | \uE0E2 複製 | \uE0E3 貼上 | \uE0E5 搜尋 |"},
            {Lang::TextEditorExitPrompt, "檔案太大，請在非Applet模式下執行！"},
        }
    }
};
