#include <switch.h>

#include "language.hpp"

// Japanese
static const char* strings_jp[] = {
    "OK",
    "キャンセル",

    "ファイルブラウザ",
    "ディレクトリリスト",
    "ファイル名",
    "サイズ",

    "オプション",
    "すべて選択",
    "すべてクリア",
    "プロパティ",
    "名前を変更",
    "新しいフォルダ",
    "新しいファイル",
    "コピー",
    "移動",
    "貼り付け",
    "削除",
    "アーカイブビットを設定",
    "名前を入力",
    "フォルダ名を入力",
    "ファイル名を入力",
    "コピー中:",

    "名前: ",
    "サイズ: ",
    "作成日: ",
    "変更日: ",
    "アクセス日: ",
    "幅: ",
    "高さ: ",

    "この操作は元に戻せません。",
    "以下のものを削除しますか:",
    "削除しますか ",

    "アーカイブを展開",
    "この操作には時間がかかる場合があります。",
    "展開しますか ",
    "展開中:",

    "設定",
    "ソート設定",
    "言語",
    "USB",
    "USBデバイスのアンマウント",
    "画像ビューア",
    "開発者オプション",
    "多言語サポート（起動速度を上げるには無効にする）",
    "フル文字セットサポート（アプレットモードでは実行できません）",
    "情報",
    "アップデートを確認",
    " ファイル名を表示",
    " ログを有効化",
    " 多言語サポートを有効化",
    " フル文字セットサポートを有効化",
    "バージョン",
    "著者",
    "バナー",

    "アップデート",
    "ネットワークに接続できませんでした。",
    "アップデートが利用可能です。",
    "NX-Shellバージョンをダウンロードしてインストールしますか ",
    "アップデートに成功しました。",
    "アプリケーションを終了して再実行してください。",
    "最新バージョンを使用しています。",

    "接続されているすべてのUSBデバイスをアンマウントしますか？",
    "USBデバイスを安全に取り外すことができるようになりました。",
    "名前を空にすることはできません。",

    // Common words
    "はい",
    "いいえ",
    "上書き",
    "挿入",
    "オン",
    "オフ",

    // Text editor strings
    "行: ",
    " 列: ",
    " | 表示: ",
    " | 更新: ",
    " | モード: ",
    " | 選択: ",
    " | Caps: ",

    "ファイル読み込み完了: ",
    "行編集: ",
    "行更新: ",
    "編集をキャンセル",
    "保存されていない変更があります！もう一度マイナスボタンを押すと終了します",
    "正常に保存されました: ",
    "エラー: ファイルの保存に失敗しました!",
    "保存する変更はありません",
    "コピーされた文字: ",
    "コピーするテキストが選択されていません",
    "クリップボードから貼り付け",
    "クリップボードは空です",
    "元に戻す成功",
    "元に戻す操作がありません",
    "やり直し成功",
    "やり直す操作がありません",
    "テキスト検索:",
    "見つかりました: \"",
    "\" 見つかりません",
    "選択モード オン",
    "選択モード オフ",
    "選択されたテキストを削除しました",
    "バックスペース (前の文字を削除)",
    "次の文字を削除",
    "新しい行を挿入",
    "| \uE0EF 保存 | \uE0F0 終了 | \uE0E0 編集 | \uE0E1 削除 | \uE0E6 元に戻す | \uE0E7 やり直す | \uE0E4+\uE0ED/\uE0EE 選択 | \uE0E2 コピー | \uE0E3 貼り付け | \uE0E5 検索 \uE0E5+\uE0EE/\uE0ED 次へ/前へ |",
};

// English
static const char* strings_en[] = {
    "OK",
    "Cancel",

    "File Browser",
    "Directory List",
    "Filename",
    "Size",

    "Options",
    "Select All",
    "Clear All",
    "Properties",
    "Rename",
    "New Folder",
    "New File",
    "Copy",
    "Move",
    "Paste",
    "Delete",
    "Set Archive Bit",
    "Enter name",
    "Enter folder name",
    "Enter file name",
    "Copying:",

    "Name: ",
    "Size: ",
    "Created: ",
    "Modified: ",
    "Accessed: ",
    "Width: ",
    "Height: ",

    "This action cannot be undone.",
    "Do you wish to delete the following:",
    "Do you wish to delete ",

    "Extract archive",
    "This action may take a while.",
    "Do you wish to extract ",
    "Extracting:",

    "Settings",
    "Sort Settings",
    "Language",
    "USB",
    "Unmount USB devices",
    "Image Viewer",
    "Developer Options",
    "Multilingual support (disable to speed up startup)",
    "Full character set support (cannot run in applet mode)",
    "About",
    "Check for Updates",
    " Display filename",
    " Enable logs",
    " Enable support for multi-language",
    " Enable support for full character set",
    "version",
    "Author",
    "Banner",

    "Update",
    "Could not connect to network.",
    "An update is available.",
    "Do you wish to download and install NX-Shell version ",
    "Update was successful.",
    "Please exit and rerun the application.",
    "You are on the latest version.",

    "Do you wish to unmount all the connected USB devices?",
    "The USB device can now be safely removed.",
    "The name cannot be empty.",

    // Common words
    "Yes",
    "No",
    "Overwrite",
    "Insert",
    "ON",
    "OFF",

    // Text editor strings
    "Line: ",
    " Col: ",
    " | View: ",
    " | Modified: ",
    " | Mode: ",
    " | Select: ",
    " | Caps: ",

    "File loaded: ", // 保持英文
    "Edit line: ",
    "Updated line: ",
    "Cancel edit",
    "Unsaved changes! Press Minus again to exit",
    "Saved successfully: ",
    "ERROR: Failed to save file!",
    "No changes to save",
    "Copied characters: ",
    "No text selected to copy",
    "Pasted from clipboard",
    "Clipboard is empty",
    "Undo successful",
    "Nothing to undo",
    "Redo successful",
    "Nothing to redo",
    "Find text:",
    "Found: \"",
    "\" not found",
    "Select mode ON",
    "Select mode OFF",
    "Deleted selected text",
    "Backspace (deleted previous character)",
    "Deleted forward character",
    "Inserted new line",
    "| \uE0EF Save | \uE0F0 Exit | \uE0E0 Edit | \uE0E1 Delete | \uE0E6 Undo | \uE0E7 Redo | \uE0E4+\uE0ED/\uE0EE Select | \uE0E2 Copy | \uE0E3 Paste | \uE0E5 Search \uE0E5+\uE0EE/\uE0ED Next/Previous |",
};

// French
static const char* strings_fr[] = {
    "OK",
    "Annuler",

    "Navigateur de fichiers",
    "Liste des répertoires",
    "Nom de fichier",
    "Taille",

    "Options",
    "Tout sélectionner",
    "Tout effacer",
    "Propriétés",
    "Renommer",
    "Nouveau dossier",
    "Nouveau fichier",
    "Copier",
    "Déplacer",
    "Coller",
    "Supprimer",
    "Définir le bit d'archive",
    "Entrez le nom",
    "Entrez le nom du dossier",
    "Entrez le nom du fichier",
    "Copie en cours:",

    "Nom: ",
    "Taille: ",
    "Création: ",
    "Modification: ",
    "Accès: ",
    "Largeur: ",
    "Hauteur: ",

    "Cette action ne peut pas être annulée.",
    "Souhaitez-vous supprimer ce qui suit:",
    "Souhaitez-vous supprimer ",

    "Extraire l'archive",
    "Cette action peut prendre un certain temps.",
    "Souhaitez-vous extraire ",
    "Extraction en cours:",

    "Paramètres",
    "Paramètres de tri",
    "Langue",
    "USB",
    "Démonter les périphériques USB",
    "Visionneuse d'images",
    "Options développeur",
    "Prise en charge multilingue (désactiver pour accélérer le démarrage)",
    "Prise en charge complète du jeu de caractères (ne peut pas être exécuté en mode applet)",
    "À propos",
    "Vérifier les mises à jour",
    " Afficher le nom du fichier",
    " Activer les logs",
    " Activer la prise en charge du multi-langue",
    " Activer la prise en charge du jeu de caractères complet",
    "version",
    "Auteur",
    "Bannière",

    "Mise à jour",
    "Impossible de se connecter au réseau.",
    "Une mise à jour est disponible.",
    "Souhaitez-vous télécharger et installer la version NX-Shell ",
    "La mise à jour a réussi.",
    "Veuillez quitter et relancer l'application.",
    "Vous disposez de la dernière version.",

    "Souhaitez-vous démonter tous les périphériques USB connectés?",
    "Le périphérique USB peut maintenant être retiré en toute sécurité.",
    "Le nom ne peut pas être vide.",

    // Common words
    "Oui",
    "Non",
    "Remplacer",
    "Insérer",
    "ACTIF",
    "INACTIF",

    // Text editor strings
    "Ligne: ",
    " Colonne: ",
    " | Vue: ",
    " | Modifié: ",
    " | Mode: ",
    " | Sélection: ",
    " | Majuscules: ",

    "Fichier chargé: ",
    "Modifier la ligne: ",
    "Ligne mise à jour : ",
    "Annuler l'édition",
    "Modifications non enregistrées ! Appuyez à nouveau sur Moins pour quitter",
    "Enregistré avec succès : ",
    "ERREUR : Échec de l'enregistrement du fichier !",
    "Aucune modification à enregistrer",
    "Caractères copiés : ",
    "Aucun texte sélectionné à copier",
    "Collé depuis le presse-papiers",
    "Le presse-papiers est vide",
    "Annulation réussie",
    "Rien à annuler",
    "Rétablissement réussi",
    "Rien à rétablir",
    "Rechercher le texte :",
    "Trouvé : \"",
    "\" non trouvé",
    "Mode sélection ACTIVÉ",
    "Mode sélection DÉSACTIVÉ",
    "Texte sélectionné supprimé",
    "Retour arrière (caractère précédent supprimé)",
    "Caractère suivant supprimé",
    "Nouvelle ligne insérée",
    "| \uE0EF Enregistrer | \uE0F0 Quitter | \uE0E0 Modifier | \uE0E1 Supprimer | \uE0E6 Annuler | \uE0E7 Rétablir | \uE0E4+\uE0ED/\uE0EE Sélectionner | \uE0E2 Copier | \uE0E3 Coller | \uE0E5 Rechercher \uE0E5+\uE0EE/\uE0ED Suivant/Précédent |",
};

// German
static const char* strings_de[] = {
    "OK",
    "Abbrechen",

    "Dateibrowser",
    "Verzeichnisliste",
    "Dateiname",
    "Größe",

    "Optionen",
    "Alle auswählen",
    "Alle löschen",
    "Eigenschaften",
    "Umbenennen",
    "Neuer Ordner",
    "Neue Datei",
    "Kopieren",
    "Verschieben",
    "Einfügen",
    "Löschen",
    "Archiv-Bit setzen",
    "Name eingeben",
    "Ordnername eingeben",
    "Dateiname eingeben",
    "Kopiere:",

    "Name: ",
    "Größe: ",
    "Erstellt: ",
    "Geändert: ",
    "Zugegriffen: ",
    "Breite: ",
    "Höhe: ",

    "Diese Aktion kann nicht rückgängig gemacht werden.",
    "Möchten Sie Folgendes löschen:",
    "Möchten Sie löschen ",

    "Archiv entpacken",
    "Dieser Vorgang kann eine Weile dauern.",
    "Möchten Sie entpacken ",
    "Entpacken:",

    "Einstellungen",
    "Sortiereinstellungen",
    "Sprache",
    "USB",
    "USB-Geräte aushängen",
    "Bildbetrachter",
    "Entwickleroptionen",
    "Mehrsprachige Unterstützung (deaktivieren zum Beschleunigen des Starts)",
    "Vollständige Zeichensatzunterstützung (kann im Applet-Modus nicht ausgeführt werden)",
    "Über",
    "Auf Updates prüfen",
    " Dateiname anzeigen",
    " Protokolle aktivieren",
    " Unterstützung für mehrere Sprachen aktivieren",
    " Unterstützung für vollständigen Zeichensatz aktivieren",
    "Version",
    "Autor",
    "Banner",

    "Update",
    "Es konnte keine Verbindung zum Netzwerk hergestellt werden.",
    "Ein Update ist verfügbar.",
    "Möchten Sie die NX-Shell-Version herunterladen und installieren? ",
    "Update war erfolgreich.",
    "Bitte beenden Sie die Anwendung und starten Sie sie erneut.",
    "Sie verwenden die neueste Version.",

    "Möchten Sie alle verbundenen USB-Geräte aushängen?",
    "Das USB-Gerät kann jetzt sicher entfernt werden.",
    "Der Name darf nicht leer sein.",

    // Common words
    "Ja",
    "Nein",
    "Überschreiben",
    "Einfügen",
    "EIN",
    "AUS",

    // Text editor strings
    "Zeile: ",
    " Spalte: ",
    " | Ansicht: ",
    " | Geändert: ",
    " | Modus: ",
    " | Auswahl: ",
    " | Feststelltaste: ",

    "Datei geladen: ",
    "Zeile bearbeiten: ",
    "Zeile aktualisiert: ",
    "Bearbeitung abbrechen",
    "Ungespeicherte Änderungen! Drücken Sie erneut Minus zum Beenden",
    "Erfolgreich gespeichert: ",
    "FEHLER: Fehler beim Speichern der Datei!",
    "Keine Änderungen zu speichern",
    "Kopierte Zeichen: ",
    "Kein Text zum Kopieren ausgewählt",
    "Aus Zwischenablage eingefügt",
    "Zwischenablage ist leer",
    "Rückgängig erfolgreich",
    "Nichts rückgängig zu machen",
    "Wiederherstellen erfolgreich",
    "Nichts zum Wiederherstellen",
    "Text suchen:",
    "Gefunden: \"",
    "\" nicht gefunden",
    "Auswahlmodus EIN",
    "Auswahlmodus AUS",
    "Ausgewählter Text gelöscht",
    "Rücktaste (vorheriges Zeichen gelöscht)",
    "Vorwärtszeichen gelöscht",
    "Neue Zeile eingefügt",
    "| \uE0EF Speichern | \uE0F0 Beenden | \uE0E0 Bearbeiten | \uE0E1 Löschen | \uE0E6 Rückgängig | \uE0E7 Wiederherstellen | \uE0E4+\uE0ED/\uE0EE Auswählen | \uE0E2 Kopieren | \uE0E3 Einfügen | \uE0E5 Suchen \uE0E5+\uE0EE/\uE0ED Nächstes/Vorheriges |",
};

// Italian
static const char* strings_it[] = {
    "OK",
    "Annulla",

    "Browser dei file",
    "Elenco delle directory",
    "Nome del file",
    "Dimensione",

    "Opzioni",
    "Seleziona tutto",
    "Cancella tutto",
    "Proprietà",
    "Rinomina",
    "Nuova cartella",
    "Nuovo file",
    "Copia",
    "Sposta",
    "Incolla",
    "Elimina",
    "Imposta il bit di archivio",
    "Inserisci nome",
    "Inserisci il nome della cartella",
    "Inserisci il nome del file",
    "Copia in corso:",

    "Nome: ",
    "Dimensione: ",
    "Creato: ",
    "Modificato: ",
    "Accesso: ",
    "Larghezza: ",
    "Altezza: ",

    "Questa azione non può essere annullata.",
    "Vuoi eliminare quanto segue:",
    "Vuoi eliminare ",

    "Estrai archivio",
    "Questa azione potrebbe richiedere un po' di tempo.",
    "Vuoi estrarre ",
    "Estrazione:",

    "Impostazioni",
    "Impostazioni di ordinamento",
    "Lingua",
    "USB",
    "Smonta dispositivi USB",
    "Visualizzatore di immagini",
    "Opzioni sviluppatore",
    "Supporto multilingue (disabilita per accelerare l'avvio)",
    "Supporto completo del set di caratteri (non può essere eseguito in modalità applet)",
    "Informazioni",
    "Controlla aggiornamenti",
    " Visualizza nome file",
    " Abilita log",
    " Abilita supporto multilingue",
    " Abilita supporto set di caratteri completo",
    "versione",
    "Autore",
    "Banner",

    "Aggiornamento",
    "Impossibile connettersi alla rete.",
    "È disponibile un aggiornamento.",
    "Vuoi scaricare e installare la versione NX-Shell ",
    "Aggiornamento riuscito.",
    "Esci e riavvia l'applicazione.",
    "Stai utilizzando la versione più recente.",

    "Vuoi smontare tutti i dispositivi USB collegati?",
    "Il dispositivo USB può ora essere rimosso in sicurezza.",
    "Il nome non può essere vuoto.",

    // Common words
    "Sì",
    "No",
    "Sovrascrivi",
    "Inserisci",
    "ON",
    "OFF",

    // Text editor strings
    "Riga: ",
    " Colonna: ",
    " | Vista: ",
    " | Modificato: ",
    " | Modalità: ",
    " | Seleziona: ",
    " | Bloc Maiusc: ",

    "File caricato: ",
    "Modifica riga: ",
    "Riga aggiornata: ",
    "Annulla modifica",
    "Modifiche non salvate! Premi di nuovo il tasto Meno per uscire",
    "Salvato con successo: ",
    "ERRORE: Impossibile salvare il file!",
    "Nessuna modifica da salvare",
    "Caratteri copiati: ",
    "Nessun testo selezionato da copiare",
    "Incollato dagli appunti",
    "Gli appunti sono vuoti",
    "Annullamento riuscito",
    "Niente da annullare",
    "Ripristino riuscito",
    "Niente da ripristinare",
    "Trova testo:",
    "Trovato: \"",
    "\" non trovato",
    "Modalità selezione ATTIVA",
    "Modalità selezione DISATTIVA",
    "Testo selezionato eliminato",
    "Backspace (carattere precedente cancellato)",
    "Carattere successivo cancellato",
    "Nuova riga inserita",
    "| \uE0EF Salvare | \uE0F0 Uscire | \uE0E0 Modificare | \uE0E1 Eliminare | \uE0E6 Annullare | \uE0E7 Ripristinare | \uE0E4+\uE0ED/\uE0EE Selezionare | \uE0E2 Copiare | \uE0E3 Incollare | \uE0E5 Cercare \uE0E5+\uE0EE/\uE0ED Successivo/Precedente |",
};

// Spanish
static const char* strings_es[] = {
    "OK",
    "Cancelar",

    "Explorador de archivos",
    "Lista de directorios",
    "Nombre de archivo",
    "Tamaño",

    "Opciones",
    "Seleccionar todo",
    "Limpiar todo",
    "Propiedades",
    "Renombrar",
    "Nueva carpeta",
    "Nuevo archivo",
    "Copiar",
    "Mover",
    "Pegar",
    "Eliminar",
    "Establecer bit de archivo",
    "Introducir nombre",
    "Introducir nombre de carpeta",
    "Introducir nombre de archivo",
    "Copiando:",

    "Nombre: ",
    "Tamaño: ",
    "Creado: ",
    "Modificado: ",
    "Accedido: ",
    "Ancho: ",
    "Alto: ",

    "Esta acción no se puede deshacer.",
    "¿Desea eliminar lo siguiente:",
    "¿Desea eliminar ",

    "Extraer archivo",
    "Esta acción puede tardar un poco.",
    "¿Desea extraer ",
    "Extrayendo:",

    "Ajustes",
    "Ajustes de ordenación",
    "Idioma",
    "USB",
    "Desmontar dispositivos USB",
    "Visor de imágenes",
    "Opciones de desarrollador",
    "Soporte multilingüe (desactivar para acelerar el inicio)",
    "Soporte completo de caracteres (no se puede ejecutar en modo applet)",
    "Acerca de",
    "Buscar actualizaciones",
    " Mostrar nombre de archivo",
    " Habilitar registros",
    " Habilitar soporte multilingüe",
    " Habilitar soporte completo de caracteres",
    "versión",
    "Autor",
    "Banner",

    "Actualización",
    "No se pudo conectar a la red.",
    "Hay una actualización disponible.",
    "¿Desea descargar e instalar la versión NX-Shell ",
    "La actualización se realizó correctamente.",
    "Por favor, salga y vuelva a ejecutar la aplicación.",
    "Está usando la última versión.",

    "¿Desea desmontar todos los dispositivos USB conectados?",
    "El dispositivo USB ahora se puede quitar de forma segura.",
    "El nombre no puede estar vacío.",

    // Common words
    "Sí",
    "No",
    "Sobrescribir",
    "Insertar",
    "ENCENDIDO",
    "APAGADO",

    // Text editor strings
    "Línea: ",
    " Columna: ",
    " | Vista: ",
    " | Modificado: ",
    " | Modo: ",
    " | Selección: ",
    " | Bloq Mayús: ",

    "Archivo cargado: ",
    "Editar línea: ",
    "Línea actualizada: ",
    "Cancelar edición",
    "¡Cambios sin guardar! Presione Menos de nuevo para salir",
    "Guardado correctamente: ",
    "ERROR: ¡Error al guardar el archivo!",
    "No hay cambios que guardar",
    "Caracteres copiados: ",
    "No hay texto seleccionado para copiar",
    "Pegado desde el portapapeles",
    "El portapapeles está vacío",
    "Deshacer exitoso",
    "Nada que deshacer",
    "Rehacer exitoso",
    "Nada que rehacer",
    "Buscar texto:",
    "Encontrado: \"",
    "\" no encontrado",
    "Modo de selección ENCENDIDO",
    "Modo de selección APAGADO",
    "Texto seleccionado eliminado",
    "Retroceso (carácter anterior eliminado)",
    "Carácter siguiente eliminado",
    "Nueva línea insertada",
    "| \uE0EF Guardar | \uE0F0 Salir | \uE0E0 Editar | \uE0E1 Eliminar | \uE0E6 Deshacer | \uE0E7 Rehacer | \uE0E4+\uE0ED/\uE0EE Seleccionar | \uE0E2 Copiar | \uE0E3 Pegar | \uE0E5 Buscar \uE0E5+\uE0EE/\uE0ED Siguiente/Anterior |",
};

// Simplified Chinese
static const char* strings_sc[] = {
    "确定",
    "取消",

    "文件浏览器",
    "目录列表",
    "文件名",
    "大小",

    "选项",
    "全选",
    "清除全部",
    "属性",
    "重命名",
    "新建文件夹",
    "新建文件",
    "复制",
    "移动",
    "粘贴",
    "删除",
    "设置存档位",
    "输入名称",
    "输入文件夹名称",
    "输入文件名",
    "复制中：",

    "名称：",
    "大小：",
    "创建日期：",
    "最后修改：",
    "最后访问：",
    "宽度：",
    "高度：",

    "本操作不可逆。",
    "确定删除下列文件吗？",
    "确定删除吗？",

    "提取归档",
    "本功能需要花费一点时间。",
    "确定提取吗？",
    "提取中：",

    "设置",
    "排序方式",
    "语言",
    "USB",
    "卸载USB设备",
    "图片查看器",
    "开发人员选项",
    "多语言支持（禁用加速启动）",
    "全字符集支持（不能在小程序模式下运行）",
    "关于",
    "检查更新",
    " 显示文件名",
    " 打开日志",
    " 启用对多语言的支持",
    " 启用对完整字符集的支持",
    "版本",
    "作者",
    "横幅",

    "更新",
    "连接网络失败。",
    "有新版本的更新可用。",
    "您希望下载并安装NX-Shell版本吗？",
    "更新成功。",
    "请退出并重新运行应用程序。",
    "您使用的是最新版本。",

    "您想卸载所有连接的USB设备吗？",
    "现在可以安全地移除USB设备。",
    "名称不能为空。",

    // Common words
    "是",
    "否",
    "覆盖",
    "插入",
    "开启",
    "关闭",

    // Text editor strings
    "行：",
    " 列：",
    " | 视图：",
    " | 已修改：",
    " | 模式：",
    " | 选择：",
    " | 大写锁定：",

    "文件已加载: ",
    "编辑行：",
    "已更新行：",
    "取消编辑",
    "未保存的更改！再次按减号退出",
    "保存成功：",
    "错误：保存文件失败！",
    "没有要保存的更改",
    "複製的字符：",
    "没有选定的文本可複製",
    "从剪贴板粘贴",
    "剪贴板为空",
    "撤销成功",
    "无可撤销操作",
    "重做成功",
    "无可重做操作",
    "查找文本：",
    "找到：\"",
    "\" 未找到",
    "选择模式 开启",
    "选择模式 关闭",
    "已删除选定文本",
    "退格键（已删除前一个字符）",
    "已删除下一个字符",
    "已插入新行",
    "| \uE0EF 保存 | \uE0F0 退出 | \uE0E0 编辑 | \uE0E1 删除 | \uE0E6 撤销 | \uE0E7 重做 | \uE0E4+\uE0ED/\uE0EE 选择 | \uE0E2 复制 | \uE0E3 粘贴 | \uE0E5 搜索 \uE0E5+\uE0EE/\uE0ED 下一个/上一个 |",
};

// Korean
static const char* strings_ko[] = {
    "확인",
    "취소",

    "파일 브라우저",
    "디렉토리 목록",
    "파일명",
    "크기",

    "옵션",
    "모두 선택",
    "모두 지우기",
    "속성",
    "이름 바꾸기",
    "새 폴더",
    "새 파일",
    "복사",
    "이동",
    "붙여넣기",
    "삭제",
    "아카이브 비트 설정",
    "이름 입력",
    "폴더 이름 입력",
    "파일 이름 입력",
    "복사 중:",

    "이름: ",
    "크기: ",
    "생성일: ",
    "수정일: ",
    "접근일: ",
    "너비: ",
    "높이: ",

    "이 작업은 취소할 수 없습니다.",
    "다음을 삭제하시겠습니까:",
    "삭제하시겠습니까 ",

    "아카이브 추출",
    "이 작업은 시간이 걸릴 수 있습니다.",
    "추출하시겠습니까 ",
    "추출 중:",

    "설정",
    "정렬 설정",
    "언어",
    "USB",
    "USB 장치 마운트 해제",
    "이미지 뷰어",
    "개발자 옵션",
    "다국어 지원 (시작 속도를 높이려면 비활성화)",
    "전체 문자 집합 지원 (애플릿 모드에서는 실행 불가)",
    "정보",
    "업데이트 확인",
    " 파일명 표시",
    " 로그 활성화",
    " 다국어 지원 활성화",
    " 전체 문자 집합 지원 활성화",
    "버전",
    "제작자",
    "배너",

    "업데이트",
    "네트워크에 연결할 수 없습니다.",
    "업데이트가 가능합니다.",
    "NX-Shell 버전을 다운로드하고 설치하시겠습니까 ",
    "업데이트에 성공했습니다.",
    "애플리케이션을 종료하고 다시 실행해 주세요.",
    "최신 버전을 사용 중입니다.",

    "연결된 모든 USB 장치의 마운트를 해제하시겠습니까?",
    "이제 USB 장치를 안전하게 제거할 수 있습니다.",
    "이름은 비어 있을 수 없습니다.",

    // Common words
    "예",
    "아니오",
    "덮어쓰기",
    "삽입",
    "켬",
    "끔",

    // Text editor strings
    "줄: ",
    " 열: ",
    " | 보기: ",
    " | 수정됨: ",
    " | 모드: ",
    " | 선택: ",
    " | Caps: ",

    "파일 로드 완료: ",
    "줄 편집: ",
    "줄 업데이트: ",
    "편집 취소",
    "저장하지 않은 변경 사항! 종료하려면 마이너스 키를 다시 누르세요",
    "성공적으로 저장됨: ",
    "오류: 파일 저장 실패!",
    "저장할 변경 사항 없음",
    "복사된 문자: ",
    "복사할 텍스트가 선택되지 않음",
    "클립보드에서 붙여넣기",
    "클립보드가 비어 있음",
    "실행 취소 성공",
    "실행 취소할 항목 없음",
    "다시 실행 성공",
    "다시 실행할 항목 없음",
    "텍스트 찾기:",
    "찾음: \"",
    "\" 찾을 수 없음",
    "선택 모드 켜짐",
    "선택 모드 끔",
    "선택한 텍스트 삭제됨",
    "백스페이스 (이전 문자 삭제됨)",
    "다음 문자 삭제됨",
    "새 줄 삽입됨",
    "| \uE0EF 저장 | \uE0F0 종료 | \uE0E0 편집 | \uE0E1 삭제 | \uE0E6 실행 취소 | \uE0E7 다시 실행 | \uE0E4+\uE0ED/\uE0EE 선택 | \uE0E2 복사 | \uE0E3 붙여넣기 | \uE0E5 검색 \uE0E5+\uE0EE/\uE0ED 다음/이전 |",
};

// Dutch
static const char* strings_nl[] = {
    "OK",
    "Annuleren",

    "Bestandsbeheerder",
    "Maplijst",
    "Bestandsnaam",
    "Grootte",

    "Opties",
    "Alles selecteren",
    "Alles wissen",
    "Eigenschappen",
    "Naam wijzigen",
    "Nieuwe map",
    "Nieuw bestand",
    "Kopiëren",
    "Verplaatsen",
    "Plakken",
    "Verwijderen",
    "Stel archiefbit in",
    "Voer naam in",
    "Voer mapnaam in",
    "Voer bestandsnaam in",
    "Kopiëren:",

    "Naam: ",
    "Grootte: ",
    "Aangemaakt: ",
    "Gewijzigd: ",
    "Geopend: ",
    "Breedte: ",
    "Hoogte: ",

    "Deze actie kan niet ongedaan worden gemaakt.",
    "Wilt u het volgende verwijderen:",
    "Wilt u verwijderen ",

    "Archief uitpakken",
    "Deze actie kan even duren.",
    "Wilt u uitpakken ",
    "Uitpakken:",

    "Instellingen",
    "Sorteerinstellingen",
    "Taal",
    "USB",
    "USB-apparaten ontkoppelen",
    "Afbeeldingsweergave",
    "Ontwikkelaarsopties",
    "Meertalige ondersteuning (uitschakelen om opstarten te versnellen)",
    "Volledige tekensetondersteuning (kan niet in appletmodus worden uitgevoerd)",
    "Over",
    "Controleren op updates",
    " Bestandsnaam weergeven",
    " Logboeken inschakelen",
    " Ondersteuning voor meerdere talen inschakelen",
    " Ondersteuning voor volledige tekenset inschakelen",
    "versie",
    "Auteur",
    "Banner",

    "Update",
    "Kan geen verbinding maken met het netwerk.",
    "Er is een update beschikbaar.",
    "Wilt u NX-Shell-versie downloaden en installeren ",
    "Update is geslaagd.",
    "Sluit af en voer de applicatie opnieuw uit.",
    "U gebruikt de nieuwste versie.",

    "Wilt u alle verbonden USB-apparaten ontkoppelen?",
    "Het USB-apparaat kan nu veilig worden verwijderd.",
    "De naam mag niet leeg zijn.",

    // Common words
    "Ja",
    "Nee",
    "Overschrijven",
    "Invoegen",
    "AAN",
    "UIT",

    // Text editor strings
    "Regel: ",
    " Kolom: ",
    " | Weergave: ",
    " | Gewijzigd: ",
    " | Modus: ",
    " | Selectie: ",
    " | Caps: ",

    "Bestand geladen: ",
    "Regel bewerken: ",
    "Regel bijgewerkt: ",
    "Bewerking annuleren",
    "Niet-opgeslagen wijzigingen! Druk opnieuw op Min om af te sluiten",
    "Succesvol opgeslagen: ",
    "FOUT: Kan bestand niet opslaan!",
    "Geen wijzigingen om op te slaan",
    "Gekopieerde tekens: ",
    "Geen tekst geselecteerd om te kopiëren",
    "Geplakt van klembord",
    "Klembord is leeg",
    "Ongedaan maken succesvol",
    "Niets om ongedaan te maken",
    "Opnieuw succesvol",
    "Niets om opnieuw te doen",
    "Tekst zoeken:",
    "Gevonden: \"",
    "\" niet gevonden",
    "Selectiemodus AAN",
    "Selectiemodus UIT",
    "Geselecteerde tekst verwijderd",
    "Backspace (vorig teken verwijderd)",
    "Volgend teken verwijderd",
    "Nieuwe regel ingevoegd",
    "| \uE0EF Opslaan | \uE0F0 Afsluiten | \uE0E0 Bewerken | \uE0E1 Verwijderen | \uE0E6 Ongedaan maken | \uE0E7 Opnieuw | \uE0E4+\uE0ED/\uE0EE Selecteren | \uE0E2 Kopiëren | \uE0E3 Plakken | \uE0E5 Zoeken \uE0E5+\uE0EE/\uE0ED Volgende/Vorige |",
};

// Portuguese
static const char* strings_pt[] = {
    "OK",
    "Cancelar",

    "Navegador de Arquivos",
    "Lista de Diretórios",
    "Nome do Arquivo",
    "Tamanho",

    "Opções",
    "Selecionar Tudo",
    "Limpar Tudo",
    "Propriedades",
    "Renomear",
    "Nova Pasta",
    "Novo Arquivo",
    "Copiar",
    "Mover",
    "Colar",
    "Excluir",
    "Definir Bit de Arquivo",
    "Digite o nome",
    "Digite o nome da pasta",
    "Digite o nome do arquivo",
    "Copiando:",

    "Nome: ",
    "Tamanho: ",
    "Criado: ",
    "Modificado: ",
    "Acessado: ",
    "Largura: ",
    "Altura: ",

    "Essa ação não pode ser desfeita.",
    "Deseja excluir o seguinte:",
    "Deseja excluir ",

    "Extrair arquivo",
    "Essa ação pode demorar um pouco.",
    "Deseja extrair ",
    "Extraindo:",

    "Configurações",
    "Configurações de Ordenação",
    "Idioma",
    "USB",
    "Desmontar Dispositivos USB",
    "Visualizador de Imagens",
    "Opções do Desenvolvedor",
    "Suporte multilíngue (desative para acelerar a inicialização)",
    "Suporte ao conjunto de caracteres completo (não pode ser executado no modo applet)",
    "Sobre",
    "Verificar Atualizações",
    " Exibir nome do arquivo",
    " Ativar logs",
    " Ativar suporte multilíngue",
    " Ativar suporte ao conjunto de caracteres completo",
    "versão",
    "Autor",
    "Banner",

    "Atualização",
    "Não foi possível conectar-se à rede.",
    "Uma atualização está disponível.",
    "Deseja baixar e instalar a versão NX-Shell ",
    "Atualização bem-sucedida.",
    "Por favor, saia e reinicie o aplicativo.",
    "Você está na versão mais recente.",

    "Deseja desmontar todos os dispositivos USB conectados?",
    "O dispositivo USB agora pode ser removido com segurança.",
    "O nome não pode estar vazio.",

    // Common words
    "Sim",
    "Não",
    "Substituir",
    "Inserir",
    "LIGADO",
    "DESLIGADO",

    // Text editor strings
    "Linha: ",
    " Coluna: ",
    " | Visualização: ",
    " | Modificado: ",
    " | Modo: ",
    " | Seleção: ",
    " | Caps: ",

    "Arquivo carregado: ",
    "Editar linha: ",
    "Linha atualizada: ",
    "Cancelar edição",
    "Alterações não salvas! Pressione Menos novamente para sair",
    "Salvo com sucesso: ",
    "ERRO: Falha ao salvar o arquivo!",
    "Nenhuma alteração para salvar",
    "Caracteres copiados: ",
    "Nenhum texto selecionado para copiar",
    "Colado da área de transferência",
    "Área de transferência vazia",
    "Desfazer bem-sucedido",
    "Nada para desfazer",
    "Refazer bem-sucedido",
    "Nada para refazer",
    "Localizar texto:",
    "Encontrado: \"",
    "\" não encontrado",
    "Modo de seleção LIGADO",
    "Modo de seleção DESLIGADO",
    "Texto selecionado excluído",
    "Backspace (caractere anterior excluído)",
    "Próximo caractere excluído",
    "Nova linha inserida",
    "| \uE0EF Salvar | \uE0F0 Sair | \uE0E0 Editar | \uE0E1 Excluir | \uE0E6 Desfazer | \uE0E7 Refazer | \uE0E4+\uE0ED/\uE0EE Selecionar | \uE0E2 Copiar | \uE0E3 Colar | \uE0E5 Pesquisar \uE0E5+\uE0EE/\uE0ED Próximo/Anterior |",
};

// Russian
static const char* strings_ru[] = {
    "OK",
    "Отмена",

    "Файловый браузер",
    "Список директорий",
    "Имя файла",
    "Размер",

    "Опции",
    "Выбрать всё",
    "Очистить всё",
    "Свойства",
    "Переименовать",
    "Новая папка",
    "Новый файл",
    "Копировать",
    "Переместить",
    "Вставить",
    "Удалить",
    "Установить бит архива",
    "Введите имя",
    "Введите имя папки",
    "Введите имя файла",
    "Копирование:",

    "Имя: ",
    "Размер: ",
    "Создан: ",
    "Изменён: ",
    "Доступ: ",
    "Ширина: ",
    "Высота: ",

    "Это действие невозможно отменить.",
    "Вы хотите удалить следующее:",
    "Вы хотите удалить ",

    "Извлечь архив",
    "Это действие может занять некоторое время.",
    "Вы хотите извлечь ",
    "Извлечение:",

    "Настройки",
    "Настройки сортировки",
    "Язык",
    "USB",
    "Отключить USB-устройства",
    "Просмотр изображений",
    "Опции разработчика",
    "Многоязычная поддержка (отключите для ускорения запуска)",
    "Поддержка полного набора символов (не может работать в режиме апплета)",
    "О программе",
    "Проверить обновления",
    " Отобразить имя файла",
    " Включить журналы",
    " Включить поддержку многоязычности",
    " Включить поддержку полного набора символов",
    "версия",
    "Автор",
    "Баннер",

    "Обновление",
    "Не удалось подключиться к сети.",
    "Доступно обновление.",
    "Вы хотите загрузить и установить версию NX-Shell ",
    "Обновление прошло успешно.",
    "Пожалуйста, выйдите и перезапустите приложение.",
    "Вы используете последнюю версию.",

    "Вы хотите отключить все подключенные USB-устройства?",
    "Теперь USB-устройство можно безопасно извлечь.",
    "Имя не может быть пустым.",

    // Common words
    "Да",
    "Нет",
    "Перезапись",
    "Вставка",
    "ВКЛ",
    "ВЫКЛ",

    // Text editor strings
    "Строка: ",
    " Столбец: ",
    " | Вид: ",
    " | Изменено: ",
    " | Режим: ",
    " | Выделение: ",
    " | Caps Lock: ",

    "Файл загружен: ",
    "Редактировать строку: ",
    "Строка обновлена: ",
    "Отменить редактирование",
    "Несохранённые изменения! Нажмите Минус ещё раз для выхода",
    "Успешно сохранено: ",
    "ОШИБКА: Не удалось сохранить файл!",
    "Нет изменений для сохранения",
    "Скопированные символы: ",
    "Нет выделенного текста для копирования",
    "Вставлено из буфера обмена",
    "Буфер обмена пуст",
    "Отмена выполнена успешно",
    "Нечего отменять",
    "Повтор выполнен успешно",
    "Нечего повторять",
    "Найти текст:",
    "Найдено: \"",
    "\" не найдено",
    "Режим выделения ВКЛ",
    "Режим выделения ВЫКЛ",
    "Выделенный текст удалён",
    "Backspace (удалён предыдущий символ)",
    "Удалён следующий символ",
    "Вставлена новая строка",
    "| \uE0EF Сохранить | \uE0F0 Выйти | \uE0E0 Редактировать | \uE0E1 Удалить | \uE0E6 Отменить | \uE0E7 Повторить | \uE0E4+\uE0ED/\uE0EE Выделить | \uE0E2 Копировать | \uE0E3 Вставить | \uE0E5 Найти \uE0E5+\uE0EE/\uE0ED Далее/Назад |",
};

// Traditional Chinese
static const char* strings_tc[] = {
    "確定",
    "取消",

    "檔案瀏覽器",
    "目錄清單",
    "檔名",
    "大小",

    "選項",
    "全選",
    "清除全部",
    "屬性",
    "重新命名",
    "新建資料夾",
    "新建檔案",
    "複製",
    "移動",
    "貼上",
    "刪除",
    "設定存檔位",
    "輸入名稱",
    "輸入資料夾名稱",
    "輸入檔名",
    "複製中：",

    "名稱：",
    "大小：",
    "建立日期：",
    "最後修改：",
    "最後訪問：",
    "寬度：",
    "高度：",

    "本操作不可逆。",
    "確定刪除下列檔案嗎？",
    "確定刪除嗎？",

    "解壓歸檔",
    "本功能需要花費一點時間。",
    "確定解壓嗎？",
    "解壓中：",

    "設定",
    "排序方式",
    "語言",
    "USB",
    "卸載USB裝置",
    "圖片檢視器",
    "開發人員選項",
    "多語言支援（停用加速啟動）",
    "全字元集支援（不能在小程式模式下執行）",
    "關於",
    "檢查更新",
    " 顯示檔名",
    " 啟用日誌",
    " 啟用對多語言的支援",
    " 啟用對完整字元集的支援",
    "版本",
    "作者",
    "橫幅",

    "更新",
    "連接網路失敗。",
    "有新版本的更新可用。",
    "您希望下載並安裝NX-Shell版本嗎？",
    "更新成功。",
    "請退出並重新執行應用程式。",
    "您使用的是最新版本。",

    "您想卸載所有連接的USB裝置嗎？",
    "現在可以安全地移除USB裝置。",
    "名稱不能為空。",

    // Common words
    "是",
    "否",
    "覆蓋",
    "插入",
    "開啟",
    "關閉",

    // Text editor strings
    "行：",
    " 列：",
    " | 檢視：",
    " | 已修改：",
    " | 模式：",
    " | 選擇：",
    " | 大寫鎖定：",

    "檔案已載入: ",
    "編輯行：",
    "已更新行：",
    "取消編輯",
    "未儲存的更改！再次按減號退出",
    "儲存成功：",
    "錯誤：儲存檔案失敗！",
    "沒有要儲存的更改",
    "複製的字元：",
    "沒有選定的文字可複製",
    "從剪貼簿貼上",
    "剪貼簿為空",
    "復原成功",
    "無可復原操作",
    "重做成功",
    "無可重做操作",
    "尋找文字：",
    "找到：\"",
    "\" 未找到",
    "選擇模式 開啟",
    "選擇模式 關閉",
    "已刪除選定文字",
    "退格鍵（已刪除前一個字元）",
    "已刪除下一個字元",
    "已插入新行",
    "| \uE0EF 儲存 | \uE0F0 退出 | \uE0E0 編輯 | \uE0E1 刪除 | \uE0E6 復原 | \uE0E7 重做 | \uE0E4+\uE0ED/\uE0EE 選擇 | \uE0E2 複製 | \uE0E3 貼上 | \uE0E5 搜尋 \uE0E5+\uE0EE/\uE0ED 下一個/上一個 |",
};

const char **strings[Lang::Max] = {
    strings_jp,
    strings_en,
    strings_fr,
    strings_de,
    strings_it,
    strings_es,
    strings_sc,
    strings_ko,
    strings_nl,
    strings_pt,
    strings_ru,
    strings_tc
};